-- per-game source handles, keyed by source: {"steam":"230410","reddit":"r/Warframe"}. a new source is
-- just a new key, no schema change. existing games are steam, so backfill their steam ref from the id.
ALTER TABLE game_display ADD COLUMN source_refs jsonb NOT NULL DEFAULT '{}'::jsonb;

UPDATE game_display SET source_refs = jsonb_build_object('steam', external_game_id::text);

-- external_game_id stops being the steam app id and becomes a pure internal id, auto-assigned from a
-- high range so a new game never collides with a row or looks like a real steam app id. existing ids
-- (all below the start) keep their values.
ALTER TABLE game_display ALTER COLUMN external_game_id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000000);
