// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package db

import (
	"context"
)

const runPatternDistribution = `-- name: RunPatternDistribution :many
WITH total AS (
    SELECT an.individual_id, count(*)::int AS n
    FROM annotations an
    WHERE an.run_id = $1 AND an.status = 'completed'
    GROUP BY an.individual_id
),
flagged AS (
    SELECT an.individual_id, m.code
    FROM annotations an
    JOIN annotation_patterns ap ON ap.annotation_id = an.id
    JOIN taxonomy_meso_levels m ON m.id = ap.pattern_id
    JOIN total t ON t.individual_id = an.individual_id
    WHERE an.run_id = $1 AND an.status = 'completed'
    GROUP BY an.individual_id, m.code, t.n
    HAVING count(*) * 2 > t.n
)
SELECT a.external_game_id, gd.name AS game_name, f.code, count(*)::int AS reviews
FROM flagged f
JOIN individuals i ON i.id = f.individual_id
JOIN artifacts a ON a.id = i.artifact_id
JOIN game_display gd ON gd.external_game_id = a.external_game_id
GROUP BY a.external_game_id, gd.name, f.code
ORDER BY a.external_game_id, reviews DESC
`

type RunPatternDistributionRow struct {
	ExternalGameID int32  `json:"external_game_id"`
	GameName       string `json:"game_name"`
	Code           string `json:"code"`
	Reviews        int32  `json:"reviews"`
}

// per game and meso code, the number of reviews in the run where a majority of the completed panel
// flagged the pattern. drives a run's detection profile: most-flagged patterns and family mix, per game
// and (summed client-side) across all games. keyed by code, stable across taxonomy versions.
func (q *Queries) RunPatternDistribution(ctx context.Context, runID int32) ([]RunPatternDistributionRow, error) {
	rows, err := q.db.Query(ctx, runPatternDistribution, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunPatternDistributionRow{}
	for rows.Next() {
		var i RunPatternDistributionRow
		if err := rows.Scan(
			&i.ExternalGameID,
			&i.GameName,
			&i.Code,
			&i.Reviews,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
