// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package db

import (
	"context"
)

const analysisAnnotations = `-- name: AnalysisAnnotations :many
SELECT
    an.individual_id,
    art.external_game_id,
    ra.model_slug,
    m.code,
    (ap.pattern_id IS NOT NULL)::bool AS present
FROM annotations an
JOIN runs r ON r.id = an.run_id
JOIN run_annotators ra ON ra.run_id = an.run_id AND ra.annotator_id = an.annotator_id
JOIN individuals i on i.id = an.individual_id
JOIN artifacts art on art.id = i.artifact_id
CROSS JOIN taxonomy_meso_levels m 
LEFT JOIN annotation_patterns ap ON ap.annotation_id = an.id AND ap.pattern_id = m.id
WHERE an.run_id = $1
    AND an.status = 'completed'
    AND m.version = r.taxonomy_version
ORDER BY an.individual_id, ra.model_slug, m.code
`

type AnalysisAnnotationsRow struct {
	IndividualID   int64  `json:"individual_id"`
	ExternalGameID int32  `json:"external_game_id"`
	ModelSlug      string `json:"model_slug"`
	Code           string `json:"code"`
	Present        bool   `json:"present"`
}

// Long format for one run: one row per (review x panel model) x pattern with present being a flag
// that indicates the model detected that pattern in the review
func (q *Queries) AnalysisAnnotations(ctx context.Context, runID int32) ([]AnalysisAnnotationsRow, error) {
	rows, err := q.db.Query(ctx, analysisAnnotations, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalysisAnnotationsRow{}
	for rows.Next() {
		var i AnalysisAnnotationsRow
		if err := rows.Scan(
			&i.IndividualID,
			&i.ExternalGameID,
			&i.ModelSlug,
			&i.Code,
			&i.Present,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analysisGold = `-- name: AnalysisGold :many
SELECT adj.individual_id,
    m.code,
    adj.pass,
    adj.final_label,
    adj.direction
FROM adjudications adj
JOIN taxonomy_meso_levels m ON m.id = adj.pattern_id
WHERE adj.run_id = $1
ORDER BY adj.individual_id, m.code, adj.pass
`

type AnalysisGoldRow struct {
	IndividualID int64  `json:"individual_id"`
	Code         string `json:"code"`
	Pass         string `json:"pass"`
	FinalLabel   bool   `json:"final_label"`
	Direction    string `json:"direction"`
}

// The adjudicated gold for a gold run, long format per (review, pattern, pass). final_label is the
// human annotator call; direction records whether it confirmed or replaced the panel majority at decision time.
func (q *Queries) AnalysisGold(ctx context.Context, goldRunID int32) ([]AnalysisGoldRow, error) {
	rows, err := q.db.Query(ctx, analysisGold, goldRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalysisGoldRow{}
	for rows.Next() {
		var i AnalysisGoldRow
		if err := rows.Scan(
			&i.IndividualID,
			&i.Code,
			&i.Pass,
			&i.FinalLabel,
			&i.Direction,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analysisStatus = `-- name: AnalysisStatus :many
SELECT
    an.individual_id,
    ra.model_slug,
    an.status,
    COALESCE(an.response_meta->>'finish_reason', '')::text AS finish_reason
FROM annotations an
JOIN run_annotators ra on ra.run_id = an.run_id and ra.annotator_id = an.annotator_id
WHERE an.run_id = $1
ORDER BY an.individual_id, ra.model_slug
`

type AnalysisStatusRow struct {
	IndividualID int64  `json:"individual_id"`
	ModelSlug    string `json:"model_slug"`
	Status       string `json:"status"`
	FinishReason string `json:"finish_reason"`
}

// The raw panel coverage for a run
func (q *Queries) AnalysisStatus(ctx context.Context, runID int32) ([]AnalysisStatusRow, error) {
	rows, err := q.db.Query(ctx, analysisStatus, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalysisStatusRow{}
	for rows.Next() {
		var i AnalysisStatusRow
		if err := rows.Scan(
			&i.IndividualID,
			&i.ModelSlug,
			&i.Status,
			&i.FinishReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runPatternDistribution = `-- name: RunPatternDistribution :many
WITH total AS (
    SELECT an.individual_id, count(*)::int AS n
    FROM annotations an
    WHERE an.run_id = $1 AND an.status = 'completed'
    GROUP BY an.individual_id
),
flagged AS (
    SELECT an.individual_id, m.code
    FROM annotations an
    JOIN annotation_patterns ap ON ap.annotation_id = an.id
    JOIN taxonomy_meso_levels m ON m.id = ap.pattern_id
    JOIN total t ON t.individual_id = an.individual_id
    WHERE an.run_id = $1 AND an.status = 'completed'
    GROUP BY an.individual_id, m.code, t.n
    HAVING count(*) * 2 > t.n
)
SELECT a.external_game_id, gd.name AS game_name, f.code, count(*)::int AS reviews
FROM flagged f
JOIN individuals i ON i.id = f.individual_id
JOIN artifacts a ON a.id = i.artifact_id
JOIN game_display gd ON gd.external_game_id = a.external_game_id
GROUP BY a.external_game_id, gd.name, f.code
ORDER BY a.external_game_id, reviews DESC
`

type RunPatternDistributionRow struct {
	ExternalGameID int32  `json:"external_game_id"`
	GameName       string `json:"game_name"`
	Code           string `json:"code"`
	Reviews        int32  `json:"reviews"`
}

// per game and meso code, the number of reviews in the run where a majority of the completed panel
// flagged the pattern. drives a run's detection profile: most-flagged patterns and family mix, per game
// and (summed client-side) across all games. keyed by code, stable across taxonomy versions.
func (q *Queries) RunPatternDistribution(ctx context.Context, runID int32) ([]RunPatternDistributionRow, error) {
	rows, err := q.db.Query(ctx, runPatternDistribution, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunPatternDistributionRow{}
	for rows.Next() {
		var i RunPatternDistributionRow
		if err := rows.Scan(
			&i.ExternalGameID,
			&i.GameName,
			&i.Code,
			&i.Reviews,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
