// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: annotation.sql

package db

import (
	"context"
)

const deleteAnnotationPatterns = `-- name: DeleteAnnotationPatterns :exec
DELETE FROM annotation_patterns WHERE annotation_id = $1
`

// Clear prior pattern rows before re-writing, so a retry doesn't leave stale ones.
func (q *Queries) DeleteAnnotationPatterns(ctx context.Context, annotationID int64) error {
	_, err := q.db.Exec(ctx, deleteAnnotationPatterns, annotationID)
	return err
}

const insertAnnotationPattern = `-- name: InsertAnnotationPattern :exec
INSERT INTO annotation_patterns (annotation_id, pattern_id, evidence, explanation)
VALUES ($1, $2, $3, $4)
ON CONFLICT (annotation_id, pattern_id) DO NOTHING
`

type InsertAnnotationPatternParams struct {
	AnnotationID int64   `json:"annotation_id"`
	PatternID    int32   `json:"pattern_id"`
	Evidence     *string `json:"evidence"`
	Explanation  *string `json:"explanation"`
}

func (q *Queries) InsertAnnotationPattern(ctx context.Context, arg InsertAnnotationPatternParams) error {
	_, err := q.db.Exec(ctx, insertAnnotationPattern,
		arg.AnnotationID,
		arg.PatternID,
		arg.Evidence,
		arg.Explanation,
	)
	return err
}

const listMesoPatternsByVersion = `-- name: ListMesoPatternsByVersion :many
SELECT
m.id,
m.code,
m.name,
m.description,
h.name as high_level_pattern
FROM taxonomy_meso_levels m
JOIN taxonomy_high_levels h ON h.id = m.parent_id
WHERE m.version = $1
ORDER BY m.code
`

type ListMesoPatternsByVersionRow struct {
	ID               int32  `json:"id"`
	Code             string `json:"code"`
	Name             string `json:"name"`
	Description      string `json:"description"`
	HighLevelPattern string `json:"high_level_pattern"`
}

// The taxonomy as of a pinned version
func (q *Queries) ListMesoPatternsByVersion(ctx context.Context, version int32) ([]ListMesoPatternsByVersionRow, error) {
	rows, err := q.db.Query(ctx, listMesoPatternsByVersion, version)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMesoPatternsByVersionRow{}
	for rows.Next() {
		var i ListMesoPatternsByVersionRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.HighLevelPattern,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
