// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: annotators.sql

package db

import (
	"context"
)

const createAnnotator = `-- name: CreateAnnotator :one
INSERT INTO annotators (kind, model_id, label)
VALUES ($1, $2, $3)
ON CONFLICT (label) DO UPDATE SET label = EXCLUDED.label
RETURNING id
`

type CreateAnnotatorParams struct {
	Kind    string `json:"kind"`
	ModelID *int32 `json:"model_id"`
	Label   string `json:"label"`
}

func (q *Queries) CreateAnnotator(ctx context.Context, arg CreateAnnotatorParams) (int32, error) {
	row := q.db.QueryRow(ctx, createAnnotator, arg.Kind, arg.ModelID, arg.Label)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getAnnotatorByLabel = `-- name: GetAnnotatorByLabel :one
SELECT id, kind, model_id, label, created_at FROM annotators WHERE label = $1
`

func (q *Queries) GetAnnotatorByLabel(ctx context.Context, label string) (Annotator, error) {
	row := q.db.QueryRow(ctx, getAnnotatorByLabel, label)
	var i Annotator
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ModelID,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const getLLMAnnotatorByModel = `-- name: GetLLMAnnotatorByModel :one
SELECT id, kind, model_id, label, created_at FROM annotators WHERE kind = 'llm' and model_id = $1
`

func (q *Queries) GetLLMAnnotatorByModel(ctx context.Context, modelID *int32) (Annotator, error) {
	row := q.db.QueryRow(ctx, getLLMAnnotatorByModel, modelID)
	var i Annotator
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ModelID,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const listAnnotators = `-- name: ListAnnotators :many
SELECT id, kind, model_id, label, created_at FROM annotators ORDER BY kind, label
`

func (q *Queries) ListAnnotators(ctx context.Context) ([]Annotator, error) {
	rows, err := q.db.Query(ctx, listAnnotators)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Annotator{}
	for rows.Next() {
		var i Annotator
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ModelID,
			&i.Label,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnnotatorsByIDs = `-- name: ListAnnotatorsByIDs :many
SELECT id, kind, model_id, label, created_at FROM annotators WHERE id = ANY($1::int[]) ORDER BY id
`

func (q *Queries) ListAnnotatorsByIDs(ctx context.Context, ids []int32) ([]Annotator, error) {
	rows, err := q.db.Query(ctx, listAnnotatorsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Annotator{}
	for rows.Next() {
		var i Annotator
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ModelID,
			&i.Label,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLLMAnnotators = `-- name: ListLLMAnnotators :many
SELECT
    a.id,
    a.label,
    m.slug,
    m.family
FROM annotators a
JOIN models m ON m.id = a.model_id
WHERE a.kind = 'llm' AND m.active
ORDER BY a.id
`

type ListLLMAnnotatorsRow struct {
	ID     int32  `json:"id"`
	Label  string `json:"label"`
	Slug   string `json:"slug"`
	Family string `json:"family"`
}

// the active LLM panel fetch from the DB with each annotator with its model slug
func (q *Queries) ListLLMAnnotators(ctx context.Context) ([]ListLLMAnnotatorsRow, error) {
	rows, err := q.db.Query(ctx, listLLMAnnotators)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLLMAnnotatorsRow{}
	for rows.Next() {
		var i ListLLMAnnotatorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Slug,
			&i.Family,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
