// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const classifyReviewsForSampling = `-- name: ClassifyReviewsForSampling :many
WITH completed AS (
    SELECT an.individual_id, count(*)::int AS n_total
    FROM annotations an WHERE an.run_id = $2 AND an.status = 'completed'
    GROUP BY an.individual_id
),
cell AS (
    SELECT an.individual_id, ap.pattern_id, count(*)::int AS n_present
    FROM annotations an JOIN annotation_patterns ap ON ap.annotation_id = an.id
    WHERE an.run_id = $2 AND an.status = 'completed'
    GROUP BY an.individual_id, ap.pattern_id
),
verdict AS (
    SELECT c.individual_id,
        bool_or(c.n_present * 2 > t.n_total) AS any_majority,
        bool_or(c.n_present > 0 AND c.n_present * 2 <= t.n_total) AS any_split
    FROM cell c JOIN completed t ON t.individual_id = c.individual_id
    GROUP BY c.individual_id
)
SELECT i.id AS individual_id, a.external_game_id,
    (CASE WHEN COALESCE(v.any_majority, false) THEN 'flagged_majority'
          WHEN COALESCE(v.any_split, false) THEN 'flagged_split'
          ELSE 'silent' END)::text AS stratum
FROM individuals i
JOIN artifacts a ON a.id = i.artifact_id
JOIN completed t ON t.individual_id = i.id
LEFT JOIN verdict v ON v.individual_id = i.id
WHERE i.population_id = $1
ORDER BY a.external_game_id, i.id
`

type ClassifyReviewsForSamplingParams struct {
	PopulationID int32 `json:"population_id"`
	PanelRunID   int32 `json:"panel_run_id"`
}

type ClassifyReviewsForSamplingRow struct {
	IndividualID   int64  `json:"individual_id"`
	ExternalGameID int32  `json:"external_game_id"`
	Stratum        string `json:"stratum"`
}

// The candidate pool for a sample: every completed review in the population, tagged with its stratum.
// A review is classified by the panel's per-pattern votes: flagged_majority if any pattern reached a
// majority Present (n_present*2 > n_total), else flagged_split if any pattern had Present votes without
// a majority (the panel disagreed), else silent (no pattern got a single Present vote).
func (q *Queries) ClassifyReviewsForSampling(ctx context.Context, arg ClassifyReviewsForSamplingParams) ([]ClassifyReviewsForSamplingRow, error) {
	rows, err := q.db.Query(ctx, classifyReviewsForSampling, arg.PopulationID, arg.PanelRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClassifyReviewsForSamplingRow{}
	for rows.Next() {
		var i ClassifyReviewsForSamplingRow
		if err := rows.Scan(&i.IndividualID, &i.ExternalGameID, &i.Stratum); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countIndividualsPerGame = `-- name: CountIndividualsPerGame :many
SELECT a.external_game_id, count(*)::int AS individuals
FROM individuals i
JOIN artifacts a ON a.id = i.artifact_id
GROUP BY a.external_game_id
ORDER BY a.external_game_id
`

type CountIndividualsPerGameRow struct {
	ExternalGameID int32 `json:"external_game_id"`
	Individuals    int32 `json:"individuals"`
}

// Curated individuals (reviews in a population) per game, across every population.
func (q *Queries) CountIndividualsPerGame(ctx context.Context) ([]CountIndividualsPerGameRow, error) {
	rows, err := q.db.Query(ctx, countIndividualsPerGame)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountIndividualsPerGameRow{}
	for rows.Next() {
		var i CountIndividualsPerGameRow
		if err := rows.Scan(&i.ExternalGameID, &i.Individuals); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const gameReviewTotals = `-- name: GameReviewTotals :many
SELECT
    a.external_game_id,
    count(DISTINCT i.id)::int AS reviews,
    count(DISTINCT i.id) FILTER (
        WHERE EXISTS (
            SELECT 1 FROM annotations an
            WHERE an.individual_id = i.id AND an.status = 'completed'
        )
    )::int AS annotated
FROM individuals i
JOIN artifacts a ON a.id = i.artifact_id
GROUP BY a.external_game_id
ORDER BY a.external_game_id
`

type GameReviewTotalsRow struct {
	ExternalGameID int32 `json:"external_game_id"`
	Reviews        int32 `json:"reviews"`
	Annotated      int32 `json:"annotated"`
}

func (q *Queries) GameReviewTotals(ctx context.Context) ([]GameReviewTotalsRow, error) {
	rows, err := q.db.Query(ctx, gameReviewTotals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GameReviewTotalsRow{}
	for rows.Next() {
		var i GameReviewTotalsRow
		if err := rows.Scan(&i.ExternalGameID, &i.Reviews, &i.Annotated); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGoldRunForPopulation = `-- name: GetGoldRunForPopulation :one
SELECT id
FROM runs
WHERE population_id = $1
    AND run_type = 'gold'
ORDER BY created_at DESC
LIMIT 1
`

// The most recent gold run for a population. Adjudication samples and decisions write into one gold
// run per population; pick the newest so a freshly drawn sample lands on the run the auditor reads.
func (q *Queries) GetGoldRunForPopulation(ctx context.Context, populationID int32) (int32, error) {
	row := q.db.QueryRow(ctx, getGoldRunForPopulation, populationID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getLatestSampleForRun = `-- name: GetLatestSampleForRun :one
SELECT id, panel_run_id, gold_run_id, strategy, seed, params, created_at
FROM adjudication_samples
WHERE panel_run_id = $1
ORDER BY created_at DESC
LIMIT 1
`

// The most recent sample drawn for a panel run, to reopen its queue.
func (q *Queries) GetLatestSampleForRun(ctx context.Context, panelRunID int32) (AdjudicationSample, error) {
	row := q.db.QueryRow(ctx, getLatestSampleForRun, panelRunID)
	var i AdjudicationSample
	err := row.Scan(
		&i.ID,
		&i.PanelRunID,
		&i.GoldRunID,
		&i.Strategy,
		&i.Seed,
		&i.Params,
		&i.CreatedAt,
	)
	return i, err
}

const getPanelRunForReview = `-- name: GetPanelRunForReview :one
SELECT r.id
FROM runs r
JOIN individuals i ON i.population_id = r.population_id
WHERE i.id = $1
    AND r.run_type = 'llm_panel'
ORDER BY r.created_at DESC
LIMIT 1
`

// The llm panel run whose votes seed a decision on this review. One panel per population; pick the
// most recent so the frozen seed reflects the panel the auditor is actually looking at.
func (q *Queries) GetPanelRunForReview(ctx context.Context, individualID int64) (int32, error) {
	row := q.db.QueryRow(ctx, getPanelRunForReview, individualID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getPatternIDByCode = `-- name: GetPatternIDByCode :one
SELECT id FROM taxonomy_meso_levels WHERE code = $1 AND version = $2
`

type GetPatternIDByCodeParams struct {
	Code    string `json:"code"`
	Version int32  `json:"version"`
}

// Resolve a meso pattern code (e.g. 'PM-1') the frontend sends to its row id, within a taxonomy
// version. Code is unique only per (code, version), so the version is required or the wrong version's
// id comes back — which would make a saved adjudication unreadable against the run's actual taxonomy.
func (q *Queries) GetPatternIDByCode(ctx context.Context, arg GetPatternIDByCodeParams) (int32, error) {
	row := q.db.QueryRow(ctx, getPatternIDByCode, arg.Code, arg.Version)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getPopulation = `-- name: GetPopulation :one
SELECT id, modality, description, created_at FROM populations WHERE id = $1
`

type GetPopulationRow struct {
	ID          int32              `json:"id"`
	Modality    string             `json:"modality"`
	Description *string            `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// One population row by id, for the population/run detail headers (modality, description, created_at).
func (q *Queries) GetPopulation(ctx context.Context, id int32) (GetPopulationRow, error) {
	row := q.db.QueryRow(ctx, getPopulation, id)
	var i GetPopulationRow
	err := row.Scan(
		&i.ID,
		&i.Modality,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getReviewMeta = `-- name: GetReviewMeta :one
SELECT a.modality,
       COALESCE(td.body, '')::text AS body,
       COALESCE(td.voted_up, false) AS voted_up,
       COALESCE(td.lang, '')::text AS lang,
       COALESCE(img.image_uri, '')::text AS image_uri,
       COALESCE(img.description, '')::text AS description,
       a.external_game_id
FROM individuals i
JOIN artifacts a ON a.id = i.artifact_id
LEFT JOIN text_review_details td ON td.artifact_id = a.id
LEFT JOIN image_details img ON img.artifact_id = a.id
WHERE i.id = $1
`

type GetReviewMetaRow struct {
	Modality       string `json:"modality"`
	Body           string `json:"body"`
	VotedUp        bool   `json:"voted_up"`
	Lang           string `json:"lang"`
	ImageUri       string `json:"image_uri"`
	Description    string `json:"description"`
	ExternalGameID int32  `json:"external_game_id"`
}

// The review header for the auditor/blind views: what to render plus the game. modality says which
// branch to render, so the joins are LEFT and the columns coalesced, a text review has no image_uri and
// an image review has no body.
func (q *Queries) GetReviewMeta(ctx context.Context, individualID int64) (GetReviewMetaRow, error) {
	row := q.db.QueryRow(ctx, getReviewMeta, individualID)
	var i GetReviewMetaRow
	err := row.Scan(
		&i.Modality,
		&i.Body,
		&i.VotedUp,
		&i.Lang,
		&i.ImageUri,
		&i.Description,
		&i.ExternalGameID,
	)
	return i, err
}

const insertAdjudicationSample = `-- name: InsertAdjudicationSample :one
INSERT INTO adjudication_samples (panel_run_id, gold_run_id, strategy, seed, params)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertAdjudicationSampleParams struct {
	PanelRunID int32           `json:"panel_run_id"`
	GoldRunID  int32           `json:"gold_run_id"`
	Strategy   string          `json:"strategy"`
	Seed       int64           `json:"seed"`
	Params     json.RawMessage `json:"params"`
}

// The sample header. params holds the per-stratum target Ns; seed is stored so the draw is auditable.
func (q *Queries) InsertAdjudicationSample(ctx context.Context, arg InsertAdjudicationSampleParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertAdjudicationSample,
		arg.PanelRunID,
		arg.GoldRunID,
		arg.Strategy,
		arg.Seed,
		arg.Params,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertAdjudicationSampleItem = `-- name: InsertAdjudicationSampleItem :exec
INSERT INTO adjudication_sample_items (sample_id, individual_id, external_game_id, stratum, selection_prob)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAdjudicationSampleItemParams struct {
	SampleID       int64   `json:"sample_id"`
	IndividualID   int64   `json:"individual_id"`
	ExternalGameID int32   `json:"external_game_id"`
	Stratum        string  `json:"stratum"`
	SelectionProb  float64 `json:"selection_prob"`
}

// One frozen member of a sample: its stratum and its inverse-probability weight (drawn / stratum_size).
func (q *Queries) InsertAdjudicationSampleItem(ctx context.Context, arg InsertAdjudicationSampleItemParams) error {
	_, err := q.db.Exec(ctx, insertAdjudicationSampleItem,
		arg.SampleID,
		arg.IndividualID,
		arg.ExternalGameID,
		arg.Stratum,
		arg.SelectionProb,
	)
	return err
}

const insertGameDisplay = `-- name: InsertGameDisplay :one
INSERT INTO game_display (external_game_id, name, short, monetization, display_color)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (external_game_id) DO UPDATE
    SET name          = EXCLUDED.name,
        short         = EXCLUDED.short,
        monetization  = EXCLUDED.monetization,
        display_color = EXCLUDED.display_color
RETURNING external_game_id, name, short, monetization, display_color
`

type InsertGameDisplayParams struct {
	ExternalGameID int32  `json:"external_game_id"`
	Name           string `json:"name"`
	Short          string `json:"short"`
	Monetization   string `json:"monetization"`
	DisplayColor   string `json:"display_color"`
}

// Register a game so it appears on the dashboard list and can be scraped.
func (q *Queries) InsertGameDisplay(ctx context.Context, arg InsertGameDisplayParams) (GameDisplay, error) {
	row := q.db.QueryRow(ctx, insertGameDisplay,
		arg.ExternalGameID,
		arg.Name,
		arg.Short,
		arg.Monetization,
		arg.DisplayColor,
	)
	var i GameDisplay
	err := row.Scan(
		&i.ExternalGameID,
		&i.Name,
		&i.Short,
		&i.Monetization,
		&i.DisplayColor,
	)
	return i, err
}

const listAnnotatorsWithModel = `-- name: ListAnnotatorsWithModel :many
SELECT
    an.id,
    an.kind,
    an.label,
    m.name AS model
FROM annotators an
LEFT JOIN models m ON m.id = an.model_id
ORDER BY an.kind, an.label
`

type ListAnnotatorsWithModelRow struct {
	ID    int32   `json:"id"`
	Kind  string  `json:"kind"`
	Label string  `json:"label"`
	Model *string `json:"model"`
}

// Every annotator as a form option, carrying the display model name for llm annotators (NULL for
// humans). ListAnnotators returns the raw rows with only a model_id; this resolves the name in SQL so
// the API never has to look models up one by one.
func (q *Queries) ListAnnotatorsWithModel(ctx context.Context) ([]ListAnnotatorsWithModelRow, error) {
	rows, err := q.db.Query(ctx, listAnnotatorsWithModel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnnotatorsWithModelRow{}
	for rows.Next() {
		var i ListAnnotatorsWithModelRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Label,
			&i.Model,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameDisplays = `-- name: ListGameDisplays :many
SELECT external_game_id, name, short, monetization, display_color
FROM game_display
ORDER BY external_game_id
`

// The curated games with their presentation metadata. external_game_id is the stable id
// the frontend uses as `gameId`; the rest are display-only fields the pipeline never needed.
func (q *Queries) ListGameDisplays(ctx context.Context) ([]GameDisplay, error) {
	rows, err := q.db.Query(ctx, listGameDisplays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GameDisplay{}
	for rows.Next() {
		var i GameDisplay
		if err := rows.Scan(
			&i.ExternalGameID,
			&i.Name,
			&i.Short,
			&i.Monetization,
			&i.DisplayColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembersForRun = `-- name: ListMembersForRun :many
SELECT
    an.id,
    an.kind,
    COALESCE(m.name, an.label) AS label
FROM runs r
JOIN annotators an ON an.id = ANY(r.annotator_ids)
LEFT JOIN models m ON m.id = an.model_id
WHERE r.id = $1
ORDER BY an.kind, an.id
`

type ListMembersForRunRow struct {
	ID    int32  `json:"id"`
	Kind  string `json:"kind"`
	Label string `json:"label"`
}

// The panel members of a run: every annotator referenced by runs.annotator_ids, with the kind
// (llm | human) and a display label. LLM members carry their model name, humans their own label.
func (q *Queries) ListMembersForRun(ctx context.Context, runID int32) ([]ListMembersForRunRow, error) {
	rows, err := q.db.Query(ctx, listMembersForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersForRunRow{}
	for rows.Next() {
		var i ListMembersForRunRow
		if err := rows.Scan(&i.ID, &i.Kind, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPopulations = `-- name: ListPopulations :many
SELECT
    p.id,
    p.modality,
    p.description,
    p.created_at,
    count(i.id)::int AS individuals
FROM populations p
LEFT JOIN individuals i ON i.population_id = p.id
GROUP BY p.id
ORDER BY p.id DESC
`

type ListPopulationsRow struct {
	ID          int32              `json:"id"`
	Modality    string             `json:"modality"`
	Description *string            `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Individuals int32              `json:"individuals"`
}

// Every population with its size (the number of frozen individuals). LEFT JOIN so an empty population
// still appears with a zero count. Newest first, the order an operator picking a population wants.
func (q *Queries) ListPopulations(ctx context.Context) ([]ListPopulationsRow, error) {
	rows, err := q.db.Query(ctx, listPopulations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPopulationsRow{}
	for rows.Next() {
		var i ListPopulationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Modality,
			&i.Description,
			&i.CreatedAt,
			&i.Individuals,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPopulationsForGame = `-- name: ListPopulationsForGame :many
SELECT
    p.id AS population_id,
    p.description,
    p.created_at,
    count(DISTINCT i.id)::int AS reviews,
    count(DISTINCT i.id) FILTER (
        WHERE EXISTS (
            SELECT 1 FROM annotations an
            WHERE an.individual_id = i.id AND an.status = 'completed'
        )
    )::int AS annotated
FROM populations p
JOIN individuals i ON i.population_id = p.id
JOIN artifacts a ON a.id = i.artifact_id
WHERE a.external_game_id = $1
GROUP BY p.id, p.description, p.created_at
ORDER BY p.id
`

type ListPopulationsForGameRow struct {
	PopulationID int32              `json:"population_id"`
	Description  *string            `json:"description"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Reviews      int32              `json:"reviews"`
	Annotated    int32              `json:"annotated"`
}

// The populations that contain this game's reviews, each with the game's slice: how many of the
// game's individuals fall in the population, and how many of those have a completed annotation. A
// population is multi-game (stratified, per-game capped), so this is THIS game's part of it. Counts
// are per population, never summed across them.
func (q *Queries) ListPopulationsForGame(ctx context.Context, externalGameID int32) ([]ListPopulationsForGameRow, error) {
	rows, err := q.db.Query(ctx, listPopulationsForGame, externalGameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPopulationsForGameRow{}
	for rows.Next() {
		var i ListPopulationsForGameRow
		if err := rows.Scan(
			&i.PopulationID,
			&i.Description,
			&i.CreatedAt,
			&i.Reviews,
			&i.Annotated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrompts = `-- name: ListPrompts :many
SELECT id, name, version, modality FROM prompts ORDER BY id
`

type ListPromptsRow struct {
	ID       int32  `json:"id"`
	Name     string `json:"name"`
	Version  int32  `json:"version"`
	Modality string `json:"modality"`
}

// Every prompt as a form option: its id, name, version and modality. Ordered by id for a stable list.
func (q *Queries) ListPrompts(ctx context.Context) ([]ListPromptsRow, error) {
	rows, err := q.db.Query(ctx, listPrompts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPromptsRow{}
	for rows.Next() {
		var i ListPromptsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.Modality,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT
    r.id,
    r.run_type,
    p.modality AS population,
    r.population_id,
    r.prompt_id,
    r.taxonomy_version,
    r.created_at,
    coalesce(array_length(r.annotator_ids, 1), 0)::int AS panel_size
FROM runs r
JOIN populations p ON p.id = r.population_id
ORDER BY r.created_at DESC
`

type ListRunsRow struct {
	ID              int32              `json:"id"`
	RunType         string             `json:"run_type"`
	Population      string             `json:"population"`
	PopulationID    int32              `json:"population_id"`
	PromptID        int32              `json:"prompt_id"`
	TaxonomyVersion *int32             `json:"taxonomy_version"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	PanelSize       int32              `json:"panel_size"`
}

// Every run with what an operator needs to recognise and pick it: its type, the population modality as a
// label, the foreign keys, the taxonomy version, when it ran, and the size of the panel it pinned.
func (q *Queries) ListRuns(ctx context.Context) ([]ListRunsRow, error) {
	rows, err := q.db.Query(ctx, listRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunsRow{}
	for rows.Next() {
		var i ListRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.RunType,
			&i.Population,
			&i.PopulationID,
			&i.PromptID,
			&i.TaxonomyVersion,
			&i.CreatedAt,
			&i.PanelSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsForDashboard = `-- name: ListRunsForDashboard :many
SELECT
    r.id,
    r.run_type,
    p.modality AS population,
    r.created_at,
    r.annotator_ids
FROM runs r
JOIN populations p ON p.id = r.population_id
ORDER BY r.created_at DESC
`

type ListRunsForDashboardRow struct {
	ID           int32              `json:"id"`
	RunType      string             `json:"run_type"`
	Population   string             `json:"population"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	AnnotatorIds []int32            `json:"annotator_ids"`
}

// One row per run with its population's modality as a human label and its creation time.
// annotator_ids is the panel the run pinned; members are resolved separately per run.
func (q *Queries) ListRunsForDashboard(ctx context.Context) ([]ListRunsForDashboardRow, error) {
	rows, err := q.db.Query(ctx, listRunsForDashboard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunsForDashboardRow{}
	for rows.Next() {
		var i ListRunsForDashboardRow
		if err := rows.Scan(
			&i.ID,
			&i.RunType,
			&i.Population,
			&i.CreatedAt,
			&i.AnnotatorIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSampleReviews = `-- name: ListSampleReviews :many
SELECT
    it.individual_id,
    it.external_game_id,
    it.stratum,
    a.modality,
    COALESCE(td.voted_up, false) AS voted_up,
    COALESCE(td.lang, '')::text AS lang,
    (
        SELECT count(*)::int
        FROM adjudications adj
        WHERE adj.run_id = s.gold_run_id
            AND adj.individual_id = it.individual_id
            AND adj.pass = $1
    ) AS decided
FROM adjudication_sample_items it
JOIN adjudication_samples s ON s.id = it.sample_id
JOIN individuals i ON i.id = it.individual_id
JOIN artifacts a ON a.id = i.artifact_id
LEFT JOIN text_review_details td ON td.artifact_id = a.id
WHERE it.sample_id = $2
ORDER BY it.external_game_id, it.individual_id
`

type ListSampleReviewsParams struct {
	Pass     string `json:"pass"`
	SampleID int64  `json:"sample_id"`
}

type ListSampleReviewsRow struct {
	IndividualID   int64  `json:"individual_id"`
	ExternalGameID int32  `json:"external_game_id"`
	Stratum        string `json:"stratum"`
	Modality       string `json:"modality"`
	VotedUp        bool   `json:"voted_up"`
	Lang           string `json:"lang"`
	Decided        int32  `json:"decided"`
}

// The queue for a sample: each selected review with the text/vote/language to render and a `decided`
// count of how many of its patterns already have a gold label in the sample's gold run, for the pass
// the screen is on. the open and blind worklists pass their own pass so each shows its own progress.
// Joining the per-review adjudication count in SQL keeps the worklist's progress one query, not N.
func (q *Queries) ListSampleReviews(ctx context.Context, arg ListSampleReviewsParams) ([]ListSampleReviewsRow, error) {
	rows, err := q.db.Query(ctx, listSampleReviews, arg.Pass, arg.SampleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSampleReviewsRow{}
	for rows.Next() {
		var i ListSampleReviewsRow
		if err := rows.Scan(
			&i.IndividualID,
			&i.ExternalGameID,
			&i.Stratum,
			&i.Modality,
			&i.VotedUp,
			&i.Lang,
			&i.Decided,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const modelStatsForGamePopulation = `-- name: ModelStatsForGamePopulation :many
SELECT
    m.name AS model,
    count(DISTINCT i.id)::int AS annotated
FROM annotations an
JOIN individuals i ON i.id = an.individual_id
JOIN artifacts a ON a.id = i.artifact_id
JOIN annotators ann ON ann.id = an.annotator_id
JOIN models m ON m.id = ann.model_id
WHERE a.external_game_id = $1
    AND i.population_id = $2
    AND an.status = 'completed'
    AND ann.kind = 'llm'
GROUP BY m.name
ORDER BY annotated DESC, m.name
`

type ModelStatsForGamePopulationParams struct {
	ExternalGameID int32 `json:"external_game_id"`
	PopulationID   int32 `json:"population_id"`
}

type ModelStatsForGamePopulationRow struct {
	Model     string `json:"model"`
	Annotated int32  `json:"annotated"`
}

// Per LLM model, the number of DISTINCT reviews of one game annotated within one population. Counting
// distinct individuals (not annotation rows) and scoping to a single population makes the models
// comparable: inside one population they all share the same work set, so a complete run shows every
// model at the population's slice size, not a runaway sum across runs.
func (q *Queries) ModelStatsForGamePopulation(ctx context.Context, arg ModelStatsForGamePopulationParams) ([]ModelStatsForGamePopulationRow, error) {
	rows, err := q.db.Query(ctx, modelStatsForGamePopulation, arg.ExternalGameID, arg.PopulationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModelStatsForGamePopulationRow{}
	for rows.Next() {
		var i ModelStatsForGamePopulationRow
		if err := rows.Scan(&i.Model, &i.Annotated); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const modelStatsForGameRun = `-- name: ModelStatsForGameRun :many
SELECT
    m.name AS model,
    count(DISTINCT i.id)::int AS annotated
FROM annotations an
JOIN individuals i ON i.id = an.individual_id
JOIN artifacts a ON a.id = i.artifact_id
JOIN annotators ann ON ann.id = an.annotator_id
JOIN models m ON m.id = ann.model_id
WHERE a.external_game_id = $1
    AND an.run_id = $2
    AND an.status = 'completed'
    AND ann.kind = 'llm'
GROUP BY m.name
ORDER BY annotated DESC, m.name
`

type ModelStatsForGameRunParams struct {
	ExternalGameID int32 `json:"external_game_id"`
	RunID          int32 `json:"run_id"`
}

type ModelStatsForGameRunRow struct {
	Model     string `json:"model"`
	Annotated int32  `json:"annotated"`
}

func (q *Queries) ModelStatsForGameRun(ctx context.Context, arg ModelStatsForGameRunParams) ([]ModelStatsForGameRunRow, error) {
	rows, err := q.db.Query(ctx, modelStatsForGameRun, arg.ExternalGameID, arg.RunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModelStatsForGameRunRow{}
	for rows.Next() {
		var i ModelStatsForGameRunRow
		if err := rows.Scan(&i.Model, &i.Annotated); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const panelForPopulation = `-- name: PanelForPopulation :many
SELECT DISTINCT
    an.kind,
    COALESCE(m.name, an.label) AS label
FROM run_annotators ra
JOIN runs r ON r.id = ra.run_id
JOIN annotators an ON an.id = ra.annotator_id
LEFT JOIN models m ON m.id = an.model_id
WHERE r.population_id = $1
ORDER BY an.kind, label
`

type PanelForPopulationRow struct {
	Kind  string `json:"kind"`
	Label string `json:"label"`
}

// The panel that worked a population: every annotator frozen onto any of the population's runs, with
// its kind (llm | human) and a display label (the model name for an llm, the annotator's own label
// for a human). run_annotators is the single source of "who annotates this run".
func (q *Queries) PanelForPopulation(ctx context.Context, populationID int32) ([]PanelForPopulationRow, error) {
	rows, err := q.db.Query(ctx, panelForPopulation, populationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PanelForPopulationRow{}
	for rows.Next() {
		var i PanelForPopulationRow
		if err := rows.Scan(&i.Kind, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const populationPerGame = `-- name: PopulationPerGame :many
SELECT
    a.external_game_id,
    count(DISTINCT i.id)::int AS reviews,
    count(DISTINCT i.id) FILTER (
        WHERE EXISTS (
            SELECT 1 FROM annotations an
            WHERE an.individual_id = i.id AND an.status = 'completed'
        )
    )::int AS annotated
FROM individuals i
JOIN artifacts a ON a.id = i.artifact_id
WHERE i.population_id = $1
GROUP BY a.external_game_id
ORDER BY a.external_game_id
`

type PopulationPerGameRow struct {
	ExternalGameID int32 `json:"external_game_id"`
	Reviews        int32 `json:"reviews"`
	Annotated      int32 `json:"annotated"`
}

// For one population, its per-game slice: how many of the population's reviews belong to each game and
// how many of those have a completed annotation. Mirrors ListPopulationsForGame but pivots to group by
// game within a single population instead of by population within a single game.
func (q *Queries) PopulationPerGame(ctx context.Context, populationID int32) ([]PopulationPerGameRow, error) {
	rows, err := q.db.Query(ctx, populationPerGame, populationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PopulationPerGameRow{}
	for rows.Next() {
		var i PopulationPerGameRow
		if err := rows.Scan(&i.ExternalGameID, &i.Reviews, &i.Annotated); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewStatsPerGame = `-- name: ReviewStatsPerGame :many
SELECT
    a.external_game_id,
    r.id AS run_id,
    p.name AS prompt,
    count(DISTINCT i.id)::int AS reviews,
    count(DISTINCT i.id) FILTER (WHERE an.status = 'completed')::int AS annotated
FROM runs r
JOIN individuals i ON i.population_id = r.population_id
JOIN artifacts a ON a.id = i.artifact_id
JOIN prompts p ON p.id = r.prompt_id
LEFT JOIN annotations an ON an.individual_id = i.id AND an.run_id = r.id
GROUP BY a.external_game_id, r.id, p.name
ORDER BY a.external_game_id, r.id
`

type ReviewStatsPerGameRow struct {
	ExternalGameID int32  `json:"external_game_id"`
	RunID          int32  `json:"run_id"`
	Prompt         string `json:"prompt"`
	Reviews        int32  `json:"reviews"`
	Annotated      int32  `json:"annotated"`
}

func (q *Queries) ReviewStatsPerGame(ctx context.Context) ([]ReviewStatsPerGameRow, error) {
	rows, err := q.db.Query(ctx, reviewStatsPerGame)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewStatsPerGameRow{}
	for rows.Next() {
		var i ReviewStatsPerGameRow
		if err := rows.Scan(
			&i.ExternalGameID,
			&i.RunID,
			&i.Prompt,
			&i.Reviews,
			&i.Annotated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
