// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countIndividualsPerGame = `-- name: CountIndividualsPerGame :many
SELECT a.external_game_id, count(*)::int AS individuals
FROM individuals i
JOIN artifacts a ON a.id = i.artifact_id
GROUP BY a.external_game_id
ORDER BY a.external_game_id
`

type CountIndividualsPerGameRow struct {
	ExternalGameID int32 `json:"external_game_id"`
	Individuals    int32 `json:"individuals"`
}

// Curated individuals (reviews in a population) per game, across every population.
func (q *Queries) CountIndividualsPerGame(ctx context.Context) ([]CountIndividualsPerGameRow, error) {
	rows, err := q.db.Query(ctx, countIndividualsPerGame)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountIndividualsPerGameRow{}
	for rows.Next() {
		var i CountIndividualsPerGameRow
		if err := rows.Scan(&i.ExternalGameID, &i.Individuals); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGoldRunForReview = `-- name: GetGoldRunForReview :one
SELECT r.id
FROM runs r
JOIN individuals i ON i.population_id = r.population_id
WHERE i.id = $1
    AND r.run_type = 'gold'
ORDER BY r.created_at DESC
LIMIT 1
`

// The gold run that adjudications for this review's population are written to. There is one gold
// run per population; pick the most recent so revisits land on the same row the queue was built from.
func (q *Queries) GetGoldRunForReview(ctx context.Context, individualID int64) (int32, error) {
	row := q.db.QueryRow(ctx, getGoldRunForReview, individualID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getPanelRunForReview = `-- name: GetPanelRunForReview :one
SELECT r.id
FROM runs r
JOIN individuals i ON i.population_id = r.population_id
WHERE i.id = $1
    AND r.run_type = 'llm_panel'
ORDER BY r.created_at DESC
LIMIT 1
`

// The llm panel run whose votes seed a decision on this review. One panel per population; pick the
// most recent so the frozen seed reflects the panel the auditor is actually looking at.
func (q *Queries) GetPanelRunForReview(ctx context.Context, individualID int64) (int32, error) {
	row := q.db.QueryRow(ctx, getPanelRunForReview, individualID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getPatternIDByCode = `-- name: GetPatternIDByCode :one
SELECT id FROM taxonomy_meso_levels WHERE code = $1
`

// Resolve a meso pattern code (e.g. 'PM-1') the frontend sends to its row id for adjudication.
func (q *Queries) GetPatternIDByCode(ctx context.Context, code string) (int32, error) {
	row := q.db.QueryRow(ctx, getPatternIDByCode, code)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const listGameDisplays = `-- name: ListGameDisplays :many
SELECT external_game_id, name, short, monetization, display_color
FROM game_display
ORDER BY external_game_id
`

// The curated games with their presentation metadata. external_game_id is the stable id
// the frontend uses as `gameId`; the rest are display-only fields the pipeline never needed.
func (q *Queries) ListGameDisplays(ctx context.Context) ([]GameDisplay, error) {
	rows, err := q.db.Query(ctx, listGameDisplays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GameDisplay{}
	for rows.Next() {
		var i GameDisplay
		if err := rows.Scan(
			&i.ExternalGameID,
			&i.Name,
			&i.Short,
			&i.Monetization,
			&i.DisplayColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembersForRun = `-- name: ListMembersForRun :many
SELECT
    an.id,
    an.kind,
    COALESCE(m.name, an.label) AS label
FROM runs r
JOIN annotators an ON an.id = ANY(r.annotator_ids)
LEFT JOIN models m ON m.id = an.model_id
WHERE r.id = $1
ORDER BY an.kind, an.id
`

type ListMembersForRunRow struct {
	ID    int32  `json:"id"`
	Kind  string `json:"kind"`
	Label string `json:"label"`
}

// The panel members of a run: every annotator referenced by runs.annotator_ids, with the kind
// (llm | human) and a display label. LLM members carry their model name, humans their own label.
func (q *Queries) ListMembersForRun(ctx context.Context, runID int32) ([]ListMembersForRunRow, error) {
	rows, err := q.db.Query(ctx, listMembersForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersForRunRow{}
	for rows.Next() {
		var i ListMembersForRunRow
		if err := rows.Scan(&i.ID, &i.Kind, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPopulationsForGame = `-- name: ListPopulationsForGame :many
SELECT
    p.id AS population_id,
    p.description,
    p.created_at,
    count(DISTINCT i.id)::int AS reviews,
    count(DISTINCT i.id) FILTER (
        WHERE EXISTS (
            SELECT 1 FROM annotations an
            WHERE an.individual_id = i.id AND an.status = 'completed'
        )
    )::int AS annotated
FROM populations p
JOIN individuals i ON i.population_id = p.id
JOIN artifacts a ON a.id = i.artifact_id
WHERE a.external_game_id = $1
GROUP BY p.id, p.description, p.created_at
ORDER BY p.id
`

type ListPopulationsForGameRow struct {
	PopulationID int32              `json:"population_id"`
	Description  *string            `json:"description"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Reviews      int32              `json:"reviews"`
	Annotated    int32              `json:"annotated"`
}

// The populations that contain this game's reviews, each with the game's slice: how many of the
// game's individuals fall in the population, and how many of those have a completed annotation. A
// population is multi-game (stratified, per-game capped), so this is THIS game's part of it. Counts
// are per population, never summed across them.
func (q *Queries) ListPopulationsForGame(ctx context.Context, externalGameID int32) ([]ListPopulationsForGameRow, error) {
	rows, err := q.db.Query(ctx, listPopulationsForGame, externalGameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPopulationsForGameRow{}
	for rows.Next() {
		var i ListPopulationsForGameRow
		if err := rows.Scan(
			&i.PopulationID,
			&i.Description,
			&i.CreatedAt,
			&i.Reviews,
			&i.Annotated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPresentPatternsForReview = `-- name: ListPresentPatternsForReview :many
SELECT
    t.code,
    t.name
FROM taxonomy_meso_levels t
JOIN annotation_patterns ap ON ap.pattern_id = t.id
JOIN annotations an ON an.id = ap.annotation_id
WHERE an.run_id = $1
    AND an.individual_id = $2
    AND an.status = 'completed'
GROUP BY t.id, t.code, t.name
HAVING count(*) * 2 > (
    SELECT count(*) FROM annotations a2
    WHERE a2.run_id = $1
        AND a2.individual_id = $2
        AND a2.status = 'completed'
)
ORDER BY t.code
`

type ListPresentPatternsForReviewParams struct {
	RunID        int32 `json:"run_id"`
	IndividualID int64 `json:"individual_id"`
}

type ListPresentPatternsForReviewRow struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

// The patterns the panel marked present on one review in one run: a pattern is present when a
// majority of the completing raters flagged it. Returns the meso code and name for each.
func (q *Queries) ListPresentPatternsForReview(ctx context.Context, arg ListPresentPatternsForReviewParams) ([]ListPresentPatternsForReviewRow, error) {
	rows, err := q.db.Query(ctx, listPresentPatternsForReview, arg.RunID, arg.IndividualID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPresentPatternsForReviewRow{}
	for rows.Next() {
		var i ListPresentPatternsForReviewRow
		if err := rows.Scan(&i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunReviews = `-- name: ListRunReviews :many
SELECT DISTINCT
    i.id AS individual_id,
    a.external_game_id,
    td.voted_up,
    td.lang,
    td.body
FROM annotations an
JOIN individuals i ON i.id = an.individual_id
JOIN artifacts a ON a.id = i.artifact_id
JOIN text_review_details td ON td.artifact_id = a.id
WHERE an.run_id = $1
ORDER BY a.external_game_id, i.id
`

type ListRunReviewsRow struct {
	IndividualID   int64  `json:"individual_id"`
	ExternalGameID int32  `json:"external_game_id"`
	VotedUp        bool   `json:"voted_up"`
	Lang           string `json:"lang"`
	Body           string `json:"body"`
}

// The adjudication queue for a run: every distinct individual (review) annotated in this run,
// with the game it belongs to and the review text/vote/language to render. One row per review.
func (q *Queries) ListRunReviews(ctx context.Context, runID int32) ([]ListRunReviewsRow, error) {
	rows, err := q.db.Query(ctx, listRunReviews, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunReviewsRow{}
	for rows.Next() {
		var i ListRunReviewsRow
		if err := rows.Scan(
			&i.IndividualID,
			&i.ExternalGameID,
			&i.VotedUp,
			&i.Lang,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsForDashboard = `-- name: ListRunsForDashboard :many
SELECT
    r.id,
    r.run_type,
    p.modality AS population,
    r.created_at,
    r.annotator_ids
FROM runs r
JOIN populations p ON p.id = r.population_id
ORDER BY r.created_at DESC
`

type ListRunsForDashboardRow struct {
	ID           int32              `json:"id"`
	RunType      string             `json:"run_type"`
	Population   string             `json:"population"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	AnnotatorIds []int32            `json:"annotator_ids"`
}

// One row per run with its population's modality as a human label and its creation time.
// annotator_ids is the panel the run pinned; members are resolved separately per run.
func (q *Queries) ListRunsForDashboard(ctx context.Context) ([]ListRunsForDashboardRow, error) {
	rows, err := q.db.Query(ctx, listRunsForDashboard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunsForDashboardRow{}
	for rows.Next() {
		var i ListRunsForDashboardRow
		if err := rows.Scan(
			&i.ID,
			&i.RunType,
			&i.Population,
			&i.CreatedAt,
			&i.AnnotatorIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const modelStatsForGame = `-- name: ModelStatsForGame :many
SELECT
    m.name AS model,
    count(*)::int AS annotated
FROM annotations an
JOIN individuals i ON i.id = an.individual_id
JOIN artifacts a ON a.id = i.artifact_id
JOIN annotators ann ON ann.id = an.annotator_id
JOIN models m ON m.id = ann.model_id
WHERE a.external_game_id = $1
    AND an.status = 'completed'
    AND ann.kind = 'llm'
GROUP BY m.name
ORDER BY annotated DESC, m.name
`

type ModelStatsForGameRow struct {
	Model     string `json:"model"`
	Annotated int32  `json:"annotated"`
}

// Per LLM model, the number of completed annotations produced on reviews of one game.
// annotators -> models gives the model name; only completed annotations are counted.
func (q *Queries) ModelStatsForGame(ctx context.Context, externalGameID int32) ([]ModelStatsForGameRow, error) {
	rows, err := q.db.Query(ctx, modelStatsForGame, externalGameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModelStatsForGameRow{}
	for rows.Next() {
		var i ModelStatsForGameRow
		if err := rows.Scan(&i.Model, &i.Annotated); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const modelStatsForGamePopulation = `-- name: ModelStatsForGamePopulation :many
SELECT
    m.name AS model,
    count(DISTINCT i.id)::int AS annotated
FROM annotations an
JOIN individuals i ON i.id = an.individual_id
JOIN artifacts a ON a.id = i.artifact_id
JOIN annotators ann ON ann.id = an.annotator_id
JOIN models m ON m.id = ann.model_id
WHERE a.external_game_id = $1
    AND i.population_id = $2
    AND an.status = 'completed'
    AND ann.kind = 'llm'
GROUP BY m.name
ORDER BY annotated DESC, m.name
`

type ModelStatsForGamePopulationParams struct {
	ExternalGameID int32 `json:"external_game_id"`
	PopulationID   int32 `json:"population_id"`
}

type ModelStatsForGamePopulationRow struct {
	Model     string `json:"model"`
	Annotated int32  `json:"annotated"`
}

// Per LLM model, the number of DISTINCT reviews of one game annotated within one population. Counting
// distinct individuals (not annotation rows) and scoping to a single population makes the models
// comparable: inside one population they all share the same work set, so a complete run shows every
// model at the population's slice size, not a runaway sum across runs.
func (q *Queries) ModelStatsForGamePopulation(ctx context.Context, arg ModelStatsForGamePopulationParams) ([]ModelStatsForGamePopulationRow, error) {
	rows, err := q.db.Query(ctx, modelStatsForGamePopulation, arg.ExternalGameID, arg.PopulationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModelStatsForGamePopulationRow{}
	for rows.Next() {
		var i ModelStatsForGamePopulationRow
		if err := rows.Scan(&i.Model, &i.Annotated); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const panelForPopulation = `-- name: PanelForPopulation :many
SELECT DISTINCT
    an.kind,
    COALESCE(m.name, an.label) AS label
FROM run_annotators ra
JOIN runs r ON r.id = ra.run_id
JOIN annotators an ON an.id = ra.annotator_id
LEFT JOIN models m ON m.id = an.model_id
WHERE r.population_id = $1
ORDER BY an.kind, label
`

type PanelForPopulationRow struct {
	Kind  string `json:"kind"`
	Label string `json:"label"`
}

// The panel that worked a population: every annotator frozen onto any of the population's runs, with
// its kind (llm | human) and a display label (the model name for an llm, the annotator's own label
// for a human). run_annotators is the single source of "who annotates this run".
func (q *Queries) PanelForPopulation(ctx context.Context, populationID int32) ([]PanelForPopulationRow, error) {
	rows, err := q.db.Query(ctx, panelForPopulation, populationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PanelForPopulationRow{}
	for rows.Next() {
		var i PanelForPopulationRow
		if err := rows.Scan(&i.Kind, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewStatsPerGame = `-- name: ReviewStatsPerGame :many
SELECT
    a.external_game_id,
    count(DISTINCT i.id)::int AS reviews,
    count(DISTINCT i.id) FILTER (
        WHERE EXISTS (
            SELECT 1 FROM annotations an
            WHERE an.individual_id = i.id AND an.status = 'completed'
        )
    )::int AS annotated
FROM individuals i
JOIN artifacts a ON a.id = i.artifact_id
GROUP BY a.external_game_id
ORDER BY a.external_game_id
`

type ReviewStatsPerGameRow struct {
	ExternalGameID int32 `json:"external_game_id"`
	Reviews        int32 `json:"reviews"`
	Annotated      int32 `json:"annotated"`
}

// Per game: how many reviews are in scope (curated individuals) and how many have at least one
// completed annotation in any run. The annotated count is distinct individuals, not annotations.
func (q *Queries) ReviewStatsPerGame(ctx context.Context) ([]ReviewStatsPerGameRow, error) {
	rows, err := q.db.Query(ctx, reviewStatsPerGame)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewStatsPerGameRow{}
	for rows.Next() {
		var i ReviewStatsPerGameRow
		if err := rows.Scan(&i.ExternalGameID, &i.Reviews, &i.Annotated); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
