// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artifacts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countArtifactsBySource = `-- name: CountArtifactsBySource :one
SELECT COUNT(*) FROM artifacts WHERE source = $1 AND modality = $2
`

type CountArtifactsBySourceParams struct {
	Source   string `json:"source"`
	Modality string `json:"modality"`
}

func (q *Queries) CountArtifactsBySource(ctx context.Context, arg CountArtifactsBySourceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countArtifactsBySource, arg.Source, arg.Modality)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getArtifact = `-- name: GetArtifact :one
SELECT id, modality, source, source_id, content_hash, scraped_at, created_at, external_game_id FROM artifacts WHERE id = $1
`

func (q *Queries) GetArtifact(ctx context.Context, id int64) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifact, id)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.Modality,
		&i.Source,
		&i.SourceID,
		&i.ContentHash,
		&i.ScrapedAt,
		&i.CreatedAt,
		&i.ExternalGameID,
	)
	return i, err
}

const upsertArtifact = `-- name: UpsertArtifact :one
INSERT INTO artifacts (modality, source, source_id, content_hash, scraped_at, external_game_id)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (source, source_id) DO UPDATE
    SET scraped_at = EXCLUDED.scraped_at
RETURNING id
`

type UpsertArtifactParams struct {
	Modality       string             `json:"modality"`
	Source         string             `json:"source"`
	SourceID       *string            `json:"source_id"`
	ContentHash    []byte             `json:"content_hash"`
	ScrapedAt      pgtype.Timestamptz `json:"scraped_at"`
	ExternalGameID int32              `json:"external_game_id"`
}

// Idempotent on source_id; DO UPDATE instead of DO NOTHING because we want it to always return the id even on re-scrape.
// ON CONFLICT we update the scraped_at date.
func (q *Queries) UpsertArtifact(ctx context.Context, arg UpsertArtifactParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertArtifact,
		arg.Modality,
		arg.Source,
		arg.SourceID,
		arg.ContentHash,
		arg.ScrapedAt,
		arg.ExternalGameID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertImageDetail = `-- name: UpsertImageDetail :exec
INSERT INTO image_details (artifact_id, image_uri, width, height, mime_type, ocr_text, description)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT DO NOTHING
`

type UpsertImageDetailParams struct {
	ArtifactID  int64   `json:"artifact_id"`
	ImageUri    string  `json:"image_uri"`
	Width       *int32  `json:"width"`
	Height      *int32  `json:"height"`
	MimeType    *string `json:"mime_type"`
	OcrText     *string `json:"ocr_text"`
	Description *string `json:"description"`
}

func (q *Queries) UpsertImageDetail(ctx context.Context, arg UpsertImageDetailParams) error {
	_, err := q.db.Exec(ctx, upsertImageDetail,
		arg.ArtifactID,
		arg.ImageUri,
		arg.Width,
		arg.Height,
		arg.MimeType,
		arg.OcrText,
		arg.Description,
	)
	return err
}

const upsertTextReviewDetail = `-- name: UpsertTextReviewDetail :exec
INSERT INTO text_review_details (artifact_id, body, voted_up, hours_played, lang, weighted_vote_score)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (artifact_id) DO UPDATE
    SET voted_up = EXCLUDED.voted_up,
        hours_played = EXCLUDED.hours_played
`

type UpsertTextReviewDetailParams struct {
	ArtifactID        int64          `json:"artifact_id"`
	Body              string         `json:"body"`
	VotedUp           bool           `json:"voted_up"`
	HoursPlayed       int32          `json:"hours_played"`
	Lang              string         `json:"lang"`
	WeightedVoteScore pgtype.Numeric `json:"weighted_vote_score"`
}

// On re-scrape we only refresh the volatile signal (votes, hours).
// body, lang and score stay as first seen on purpose, so annotation always line up with the text they ran on.
// An edited review is a new artifact if we ever want to recapture it.
func (q *Queries) UpsertTextReviewDetail(ctx context.Context, arg UpsertTextReviewDetailParams) error {
	_, err := q.db.Exec(ctx, upsertTextReviewDetail,
		arg.ArtifactID,
		arg.Body,
		arg.VotedUp,
		arg.HoursPlayed,
		arg.Lang,
		arg.WeightedVoteScore,
	)
	return err
}
