// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comparisons.sql

package db

import (
	"context"
	"encoding/json"
)

const comparisonModelAgreement = `-- name: ComparisonModelAgreement :many
WITH shared_models AS (
    SELECT ra.model_slug FROM run_annotators ra WHERE ra.run_id = $1
    INTERSECT
    SELECT ra.model_slug FROM run_annotators ra WHERE ra.run_id = $2
),
shared_reviews AS (
    SELECT an.individual_id FROM annotations an WHERE an.run_id = $1 AND an.status = 'completed'
    INTERSECT
    SELECT an.individual_id FROM annotations an WHERE an.run_id = $2 AND an.status = 'completed'
),
a_cells AS (
    SELECT ra.model_slug, an.individual_id, m.code
    FROM annotations an
    JOIN run_annotators ra ON ra.run_id = an.run_id AND ra.annotator_id = an.annotator_id
    JOIN annotation_patterns ap ON ap.annotation_id = an.id
    JOIN taxonomy_meso_levels m ON m.id = ap.pattern_id
    WHERE an.run_id = $1 AND an.status = 'completed'
        AND ra.model_slug IN (SELECT model_slug FROM shared_models)
        AND an.individual_id IN (SELECT individual_id FROM shared_reviews)
),
b_cells AS (
    SELECT ra.model_slug, an.individual_id, m.code
    FROM annotations an
    JOIN run_annotators ra ON ra.run_id = an.run_id AND ra.annotator_id = an.annotator_id
    JOIN annotation_patterns ap ON ap.annotation_id = an.id
    JOIN taxonomy_meso_levels m ON m.id = ap.pattern_id
    WHERE an.run_id = $2 AND an.status = 'completed'
        AND ra.model_slug IN (SELECT model_slug FROM shared_models)
        AND an.individual_id IN (SELECT individual_id FROM shared_reviews)
),
joined AS (
    SELECT COALESCE(a.model_slug, b.model_slug) AS model_slug,
        (a.code IS NOT NULL) AS in_a,
        (b.code IS NOT NULL) AS in_b
    FROM a_cells a
    FULL OUTER JOIN b_cells b
        ON a.model_slug = b.model_slug
        AND a.individual_id = b.individual_id
        AND a.code = b.code
)
SELECT model_slug,
    count(*) FILTER (WHERE in_a AND in_b)::int AS agreed_present,
    count(*) FILTER (WHERE in_a <> in_b)::int AS flips
FROM joined
GROUP BY model_slug
ORDER BY model_slug
`

type ComparisonModelAgreementParams struct {
	RunA int32 `json:"run_a"`
	RunB int32 `json:"run_b"`
}

type ComparisonModelAgreementRow struct {
	ModelSlug     string `json:"model_slug"`
	AgreedPresent int32  `json:"agreed_present"`
	Flips         int32  `json:"flips"`
}

// per shared model (in both panels), how many flagged patterns both runs agreed on vs flipped, across
// the shared reviews. the universe is the union of present-cells for that model; mutual absence is not
// counted. keyed by the meso code so it is stable across taxonomy versions.
func (q *Queries) ComparisonModelAgreement(ctx context.Context, arg ComparisonModelAgreementParams) ([]ComparisonModelAgreementRow, error) {
	rows, err := q.db.Query(ctx, comparisonModelAgreement, arg.RunA, arg.RunB)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComparisonModelAgreementRow{}
	for rows.Next() {
		var i ComparisonModelAgreementRow
		if err := rows.Scan(&i.ModelSlug, &i.AgreedPresent, &i.Flips); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const comparisonReviewDivergence = `-- name: ComparisonReviewDivergence :many
WITH shared_reviews AS (
    SELECT an.individual_id FROM annotations an WHERE an.run_id = $1 AND an.status = 'completed'
    INTERSECT
    SELECT an.individual_id FROM annotations an WHERE an.run_id = $2 AND an.status = 'completed'
),
a_total AS (
    SELECT an.individual_id, count(*)::int AS n
    FROM annotations an WHERE an.run_id = $1 AND an.status = 'completed'
    GROUP BY an.individual_id
),
b_total AS (
    SELECT an.individual_id, count(*)::int AS n
    FROM annotations an WHERE an.run_id = $2 AND an.status = 'completed'
    GROUP BY an.individual_id
),
a_flagged AS (
    SELECT an.individual_id, m.code
    FROM annotations an
    JOIN annotation_patterns ap ON ap.annotation_id = an.id
    JOIN taxonomy_meso_levels m ON m.id = ap.pattern_id
    JOIN a_total t ON t.individual_id = an.individual_id
    WHERE an.run_id = $1 AND an.status = 'completed'
    GROUP BY an.individual_id, m.code, t.n
    HAVING count(*) * 2 > t.n
),
b_flagged AS (
    SELECT an.individual_id, m.code
    FROM annotations an
    JOIN annotation_patterns ap ON ap.annotation_id = an.id
    JOIN taxonomy_meso_levels m ON m.id = ap.pattern_id
    JOIN b_total t ON t.individual_id = an.individual_id
    WHERE an.run_id = $2 AND an.status = 'completed'
    GROUP BY an.individual_id, m.code, t.n
    HAVING count(*) * 2 > t.n
),
flips AS (
    SELECT COALESCE(a.individual_id, b.individual_id) AS individual_id, count(*)::int AS flips
    FROM a_flagged a
    FULL OUTER JOIN b_flagged b ON a.individual_id = b.individual_id AND a.code = b.code
    WHERE a.code IS NULL OR b.code IS NULL
    GROUP BY COALESCE(a.individual_id, b.individual_id)
)
SELECT sr.individual_id,
    art.external_game_id,
    COALESCE(f.flips, 0)::int AS flips
FROM shared_reviews sr
JOIN individuals i ON i.id = sr.individual_id
JOIN artifacts art ON art.id = i.artifact_id
LEFT JOIN flips f ON f.individual_id = sr.individual_id
ORDER BY COALESCE(f.flips, 0) DESC, art.external_game_id, sr.individual_id
`

type ComparisonReviewDivergenceParams struct {
	RunA int32 `json:"run_a"`
	RunB int32 `json:"run_b"`
}

type ComparisonReviewDivergenceRow struct {
	IndividualID   int64 `json:"individual_id"`
	ExternalGameID int32 `json:"external_game_id"`
	Flips          int32 `json:"flips"`
}

// the worklist: every review both runs annotated, with how many patterns the two panels disagreed on.
// this works for any two runs (same or different panels): each panel's verdict on a pattern is whether a
// strict majority of its completed members flagged it; a flip is a pattern one panel's majority flagged
// and the other's did not. patterns are keyed by meso code (stable across taxonomy versions). the
// per-model detail lives in the drill-down.
func (q *Queries) ComparisonReviewDivergence(ctx context.Context, arg ComparisonReviewDivergenceParams) ([]ComparisonReviewDivergenceRow, error) {
	rows, err := q.db.Query(ctx, comparisonReviewDivergence, arg.RunA, arg.RunB)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComparisonReviewDivergenceRow{}
	for rows.Next() {
		var i ComparisonReviewDivergenceRow
		if err := rows.Scan(&i.IndividualID, &i.ExternalGameID, &i.Flips); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteComparison = `-- name: DeleteComparison :exec
DELETE FROM comparisons WHERE id = $1
`

func (q *Queries) DeleteComparison(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteComparison, id)
	return err
}

const getComparison = `-- name: GetComparison :one
SELECT id, label, run_a_id, run_b_id, contract, created_at FROM comparisons WHERE id = $1
`

func (q *Queries) GetComparison(ctx context.Context, id int32) (Comparison, error) {
	row := q.db.QueryRow(ctx, getComparison, id)
	var i Comparison
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.RunAID,
		&i.RunBID,
		&i.Contract,
		&i.CreatedAt,
	)
	return i, err
}

const insertComparison = `-- name: InsertComparison :one
INSERT INTO comparisons (label, run_a_id, run_b_id, contract)
VALUES ($1, $2, $3, $4)
RETURNING id, label, run_a_id, run_b_id, contract, created_at
`

type InsertComparisonParams struct {
	Label    string          `json:"label"`
	RunAID   int32           `json:"run_a_id"`
	RunBID   int32           `json:"run_b_id"`
	Contract json.RawMessage `json:"contract"`
}

func (q *Queries) InsertComparison(ctx context.Context, arg InsertComparisonParams) (Comparison, error) {
	row := q.db.QueryRow(ctx, insertComparison,
		arg.Label,
		arg.RunAID,
		arg.RunBID,
		arg.Contract,
	)
	var i Comparison
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.RunAID,
		&i.RunBID,
		&i.Contract,
		&i.CreatedAt,
	)
	return i, err
}

const listComparisons = `-- name: ListComparisons :many
SELECT id, label, run_a_id, run_b_id, contract, created_at FROM comparisons ORDER BY created_at DESC
`

func (q *Queries) ListComparisons(ctx context.Context) ([]Comparison, error) {
	rows, err := q.db.Query(ctx, listComparisons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comparison{}
	for rows.Next() {
		var i Comparison
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.RunAID,
			&i.RunBID,
			&i.Contract,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
