// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: crud.sql

package db

import (
	"context"
	"encoding/json"
)

const countAnnotatorRefs = `-- name: CountAnnotatorRefs :one
SELECT
    (SELECT count(*) FROM run_annotators ra WHERE ra.annotator_id = $1)::int +
    (SELECT count(*) FROM annotations an WHERE an.annotator_id = $1)::int AS ref_count
`

func (q *Queries) CountAnnotatorRefs(ctx context.Context, annotatorID int32) (int32, error) {
	row := q.db.QueryRow(ctx, countAnnotatorRefs, annotatorID)
	var ref_count int32
	err := row.Scan(&ref_count)
	return ref_count, err
}

const countArtifactsForGame = `-- name: CountArtifactsForGame :one
SELECT count(*)::int FROM artifacts WHERE external_game_id = $1
`

func (q *Queries) CountArtifactsForGame(ctx context.Context, externalGameID int32) (int32, error) {
	row := q.db.QueryRow(ctx, countArtifactsForGame, externalGameID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countRunsForPrompt = `-- name: CountRunsForPrompt :one
SELECT count(*)::int FROM runs WHERE prompt_id = $1
`

func (q *Queries) CountRunsForPrompt(ctx context.Context, promptID int32) (int32, error) {
	row := q.db.QueryRow(ctx, countRunsForPrompt, promptID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteAdjudicationSamplesByRun = `-- name: DeleteAdjudicationSamplesByRun :exec
DELETE FROM adjudication_samples WHERE panel_run_id = $1 OR gold_run_id = $1
`

// sample items cascade on the sample delete.
func (q *Queries) DeleteAdjudicationSamplesByRun(ctx context.Context, panelRunID int32) error {
	_, err := q.db.Exec(ctx, deleteAdjudicationSamplesByRun, panelRunID)
	return err
}

const deleteAdjudicationsByRun = `-- name: DeleteAdjudicationsByRun :exec
DELETE FROM adjudications WHERE run_id = $1
`

func (q *Queries) DeleteAdjudicationsByRun(ctx context.Context, runID int32) error {
	_, err := q.db.Exec(ctx, deleteAdjudicationsByRun, runID)
	return err
}

const deleteAnnotationPatternsByRun = `-- name: DeleteAnnotationPatternsByRun :exec
DELETE FROM annotation_patterns
WHERE annotation_id IN (SELECT id FROM annotations WHERE run_id = $1)
`

func (q *Queries) DeleteAnnotationPatternsByRun(ctx context.Context, runID int32) error {
	_, err := q.db.Exec(ctx, deleteAnnotationPatternsByRun, runID)
	return err
}

const deleteAnnotationsByRun = `-- name: DeleteAnnotationsByRun :exec
DELETE FROM annotations WHERE run_id = $1
`

func (q *Queries) DeleteAnnotationsByRun(ctx context.Context, runID int32) error {
	_, err := q.db.Exec(ctx, deleteAnnotationsByRun, runID)
	return err
}

const deleteAnnotator = `-- name: DeleteAnnotator :exec
DELETE FROM annotators WHERE id = $1
`

func (q *Queries) DeleteAnnotator(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteAnnotator, id)
	return err
}

const deleteGameDisplay = `-- name: DeleteGameDisplay :exec
DELETE FROM game_display WHERE external_game_id = $1
`

func (q *Queries) DeleteGameDisplay(ctx context.Context, externalGameID int32) error {
	_, err := q.db.Exec(ctx, deleteGameDisplay, externalGameID)
	return err
}

const deleteIndividualsByPopulation = `-- name: DeleteIndividualsByPopulation :exec
DELETE FROM individuals WHERE population_id = $1
`

func (q *Queries) DeleteIndividualsByPopulation(ctx context.Context, populationID int32) error {
	_, err := q.db.Exec(ctx, deleteIndividualsByPopulation, populationID)
	return err
}

const deletePopulation = `-- name: DeletePopulation :exec
DELETE FROM populations WHERE id = $1
`

func (q *Queries) DeletePopulation(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePopulation, id)
	return err
}

const deletePrompt = `-- name: DeletePrompt :exec
DELETE FROM prompts WHERE id = $1
`

func (q *Queries) DeletePrompt(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePrompt, id)
	return err
}

const deleteRun = `-- name: DeleteRun :exec
DELETE FROM runs WHERE id = $1
`

// run_annotators cascade on the run delete.
func (q *Queries) DeleteRun(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteRun, id)
	return err
}

const gameArtifactTotals = `-- name: GameArtifactTotals :many
SELECT external_game_id, count(*)::int AS artifacts
FROM artifacts
GROUP BY external_game_id
`

type GameArtifactTotalsRow struct {
	ExternalGameID int32 `json:"external_game_id"`
	Artifacts      int32 `json:"artifacts"`
}

// artifacts per game, the delete guard: a game with any artifact is frozen.
func (q *Queries) GameArtifactTotals(ctx context.Context) ([]GameArtifactTotalsRow, error) {
	rows, err := q.db.Query(ctx, gameArtifactTotals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GameArtifactTotalsRow{}
	for rows.Next() {
		var i GameArtifactTotalsRow
		if err := rows.Scan(&i.ExternalGameID, &i.Artifacts); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameDisplay = `-- name: GetGameDisplay :one
SELECT external_game_id, name, short, monetization, display_color, source_refs FROM game_display WHERE external_game_id = $1
`

func (q *Queries) GetGameDisplay(ctx context.Context, externalGameID int32) (GameDisplay, error) {
	row := q.db.QueryRow(ctx, getGameDisplay, externalGameID)
	var i GameDisplay
	err := row.Scan(
		&i.ExternalGameID,
		&i.Name,
		&i.Short,
		&i.Monetization,
		&i.DisplayColor,
		&i.SourceRefs,
	)
	return i, err
}

const getGameSourceRef = `-- name: GetGameSourceRef :one
SELECT COALESCE(source_refs->>$1::text, '')::text AS handle
FROM game_display
WHERE external_game_id = $2
`

type GetGameSourceRefParams struct {
	Source         string `json:"source"`
	ExternalGameID int32  `json:"external_game_id"`
}

// the scrape handle a game registered for one source (e.g. its subreddit for 'reddit'). empty when the
// game has no binding for that source.
func (q *Queries) GetGameSourceRef(ctx context.Context, arg GetGameSourceRefParams) (string, error) {
	row := q.db.QueryRow(ctx, getGameSourceRef, arg.Source, arg.ExternalGameID)
	var handle string
	err := row.Scan(&handle)
	return handle, err
}

const listRunIDsByPopulation = `-- name: ListRunIDsByPopulation :many
SELECT id FROM runs WHERE population_id = $1
`

func (q *Queries) ListRunIDsByPopulation(ctx context.Context, populationID int32) ([]int32, error) {
	rows, err := q.db.Query(ctx, listRunIDsByPopulation, populationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const populationImpact = `-- name: PopulationImpact :one
SELECT
    (SELECT count(*) FROM individuals i WHERE i.population_id = $1)::int AS individuals,
    (SELECT count(*) FROM runs r WHERE r.population_id = $1)::int AS runs,
    (SELECT count(*) FROM annotations an JOIN runs r ON r.id = an.run_id WHERE r.population_id = $1)::int AS annotations,
    (SELECT count(*) FROM adjudication_samples s JOIN runs r ON r.id = s.panel_run_id WHERE r.population_id = $1)::int AS samples
`

type PopulationImpactRow struct {
	Individuals int32 `json:"individuals"`
	Runs        int32 `json:"runs"`
	Annotations int32 `json:"annotations"`
	Samples     int32 `json:"samples"`
}

// the blast radius of deleting a population: its individuals, the runs over it, and those runs
// annotations and adjudication samples.
func (q *Queries) PopulationImpact(ctx context.Context, populationID int32) (PopulationImpactRow, error) {
	row := q.db.QueryRow(ctx, populationImpact, populationID)
	var i PopulationImpactRow
	err := row.Scan(
		&i.Individuals,
		&i.Runs,
		&i.Annotations,
		&i.Samples,
	)
	return i, err
}

const runImpact = `-- name: RunImpact :one
SELECT
    (SELECT count(*) FROM annotations an WHERE an.run_id = $1)::int AS annotations,
    (SELECT count(*) FROM adjudication_samples s WHERE s.panel_run_id = $1 OR s.gold_run_id = $1)::int AS samples,
    (SELECT count(*) FROM adjudications adj WHERE adj.run_id = $1)::int AS adjudications
`

type RunImpactRow struct {
	Annotations   int32 `json:"annotations"`
	Samples       int32 `json:"samples"`
	Adjudications int32 `json:"adjudications"`
}

// the blast radius of deleting a run: its annotations, the adjudication samples it seeds (as panel or
// gold), and its adjudications.
func (q *Queries) RunImpact(ctx context.Context, runID int32) (RunImpactRow, error) {
	row := q.db.QueryRow(ctx, runImpact, runID)
	var i RunImpactRow
	err := row.Scan(&i.Annotations, &i.Samples, &i.Adjudications)
	return i, err
}

const updateAnnotatorLabel = `-- name: UpdateAnnotatorLabel :exec
UPDATE annotators SET label = $2 WHERE id = $1
`

type UpdateAnnotatorLabelParams struct {
	ID    int32  `json:"id"`
	Label string `json:"label"`
}

func (q *Queries) UpdateAnnotatorLabel(ctx context.Context, arg UpdateAnnotatorLabelParams) error {
	_, err := q.db.Exec(ctx, updateAnnotatorLabel, arg.ID, arg.Label)
	return err
}

const updateGameDisplay = `-- name: UpdateGameDisplay :one
UPDATE game_display
SET name          = $2,
    short         = $3,
    monetization  = $4,
    display_color = $5,
    source_refs   = $6
WHERE external_game_id = $1
RETURNING external_game_id, name, short, monetization, display_color, source_refs
`

type UpdateGameDisplayParams struct {
	ExternalGameID int32           `json:"external_game_id"`
	Name           string          `json:"name"`
	Short          string          `json:"short"`
	Monetization   string          `json:"monetization"`
	DisplayColor   string          `json:"display_color"`
	SourceRefs     json.RawMessage `json:"source_refs"`
}

// edit a games display fields and its per-source handles.
func (q *Queries) UpdateGameDisplay(ctx context.Context, arg UpdateGameDisplayParams) (GameDisplay, error) {
	row := q.db.QueryRow(ctx, updateGameDisplay,
		arg.ExternalGameID,
		arg.Name,
		arg.Short,
		arg.Monetization,
		arg.DisplayColor,
		arg.SourceRefs,
	)
	var i GameDisplay
	err := row.Scan(
		&i.ExternalGameID,
		&i.Name,
		&i.Short,
		&i.Monetization,
		&i.DisplayColor,
		&i.SourceRefs,
	)
	return i, err
}

const updatePrompt = `-- name: UpdatePrompt :exec
UPDATE prompts
SET name = $2, version = $3, modality = $4, system_prompt = $5, template = $6
WHERE id = $1
`

type UpdatePromptParams struct {
	ID           int32   `json:"id"`
	Name         string  `json:"name"`
	Version      int32   `json:"version"`
	Modality     string  `json:"modality"`
	SystemPrompt *string `json:"system_prompt"`
	Template     string  `json:"template"`
}

func (q *Queries) UpdatePrompt(ctx context.Context, arg UpdatePromptParams) error {
	_, err := q.db.Exec(ctx, updatePrompt,
		arg.ID,
		arg.Name,
		arg.Version,
		arg.Modality,
		arg.SystemPrompt,
		arg.Template,
	)
	return err
}
