// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: curation.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addIndividual = `-- name: AddIndividual :exec
INSERT INTO individuals (population_id, artifact_id)
VALUES ($1, $2)
ON CONFLICT (population_id, artifact_id) DO NOTHING
`

type AddIndividualParams struct {
	PopulationID int32 `json:"population_id"`
	ArtifactID   int64 `json:"artifact_id"`
}

func (q *Queries) AddIndividual(ctx context.Context, arg AddIndividualParams) error {
	_, err := q.db.Exec(ctx, addIndividual, arg.PopulationID, arg.ArtifactID)
	return err
}

const countIndividuals = `-- name: CountIndividuals :one
SELECT count(*) FROM individuals WHERE population_id = $1
`

func (q *Queries) CountIndividuals(ctx context.Context, populationID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countIndividuals, populationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPopulation = `-- name: CreatePopulation :one
INSERT INTO populations (modality, description, criteria, artifacts_cutoff)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreatePopulationParams struct {
	Modality        string             `json:"modality"`
	Description     *string            `json:"description"`
	Criteria        []byte             `json:"criteria"`
	ArtifactsCutoff pgtype.Timestamptz `json:"artifacts_cutoff"`
}

func (q *Queries) CreatePopulation(ctx context.Context, arg CreatePopulationParams) (int32, error) {
	row := q.db.QueryRow(ctx, createPopulation,
		arg.Modality,
		arg.Description,
		arg.Criteria,
		arg.ArtifactsCutoff,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const freezeStratifiedPopulation = `-- name: FreezeStratifiedPopulation :execrows
INSERT INTO individuals (population_id, artifact_id)
SELECT $1::int, ranked.artifact_id
FROM (
    SELECT a.id as artifact_id,
           row_number() OVER (
            PARTITION BY a.external_game_id
            ORDER BY a.id
           ) as rn
    FROM artifacts a
    JOIN text_review_details td ON td.artifact_id = a.id
    WHERE a.modality = 'text'
        AND a.scraped_at <= $2
        AND td.hours_played >= $3::int
        -- an empty or null game list means all games, otherwise keep only the picked ones. coalesce so
        -- a null array reads as 0, same as empty, instead of dropping every row.
        AND (coalesce(cardinality($4::int[]), 0) = 0 OR a.external_game_id = ANY($4::int[]))
) ranked
WHERE ranked.rn <= $5::int
ON CONFLICT (population_id, artifact_id) DO NOTHING
`

type FreezeStratifiedPopulationParams struct {
	PopulationID    int32              `json:"population_id"`
	ArtifactsCutoff pgtype.Timestamptz `json:"artifacts_cutoff"`
	MinHoursPlayed  int32              `json:"min_hours_played"`
	GameIds         []int32            `json:"game_ids"`
	PerGameCap      int32              `json:"per_game_cap"`
}

func (q *Queries) FreezeStratifiedPopulation(ctx context.Context, arg FreezeStratifiedPopulationParams) (int64, error) {
	result, err := q.db.Exec(ctx, freezeStratifiedPopulation,
		arg.PopulationID,
		arg.ArtifactsCutoff,
		arg.MinHoursPlayed,
		arg.GameIds,
		arg.PerGameCap,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const selectTextReviewsFromPopulation = `-- name: SelectTextReviewsFromPopulation :many
SELECT
FROM artifacts a
JOIN text_review_details td ON td.artifact_id = a.id
WHERE a.modality = 'text'
    AND a.scraped_at <= $1
    AND td.hours_played >= $2
`

type SelectTextReviewsFromPopulationParams struct {
	ScrapedAt   pgtype.Timestamptz `json:"scraped_at"`
	HoursPlayed int32              `json:"hours_played"`
}

type SelectTextReviewsFromPopulationRow struct {
}

// Representative selection with common filters and the cutoff
// Criteria need dynamic SQL
func (q *Queries) SelectTextReviewsFromPopulation(ctx context.Context, arg SelectTextReviewsFromPopulationParams) ([]SelectTextReviewsFromPopulationRow, error) {
	rows, err := q.db.Query(ctx, selectTextReviewsFromPopulation, arg.ScrapedAt, arg.HoursPlayed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectTextReviewsFromPopulationRow{}
	for rows.Next() {
		var i SelectTextReviewsFromPopulationRow
		if err := rows.Scan(); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
