// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: game_descriptions.sql

package db

import (
	"context"
	"encoding/json"
)

const approveDescription = `-- name: ApproveDescription :one
UPDATE game_descriptions
SET status = 'approved', approved_by = $2, approved_at = now()
WHERE id = $1 AND status = 'draft' AND valence_flags = '[]'::jsonb
RETURNING id, external_game_id, version, status, profile, rendered_text, research_model, sources, valence_flags, error, content_hash, created_at, approved_by, approved_at
`

type ApproveDescriptionParams struct {
	ID         int32  `json:"id"`
	ApprovedBy *int32 `json:"approved_by"`
}

// freeze a draft as the approved version. blocked unless it is a draft with no unresolved valence flags.
func (q *Queries) ApproveDescription(ctx context.Context, arg ApproveDescriptionParams) (GameDescription, error) {
	row := q.db.QueryRow(ctx, approveDescription, arg.ID, arg.ApprovedBy)
	var i GameDescription
	err := row.Scan(
		&i.ID,
		&i.ExternalGameID,
		&i.Version,
		&i.Status,
		&i.Profile,
		&i.RenderedText,
		&i.ResearchModel,
		&i.Sources,
		&i.ValenceFlags,
		&i.Error,
		&i.ContentHash,
		&i.CreatedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
	)
	return i, err
}

const gamesMissingApprovedDescription = `-- name: GamesMissingApprovedDescription :many
SELECT DISTINCT a.external_game_id, gd.name
FROM individuals i
JOIN artifacts a ON a.id = i.artifact_id
JOIN game_display gd ON gd.external_game_id = a.external_game_id
WHERE i.population_id = $1
    AND NOT EXISTS (
        SELECT 1 FROM game_descriptions d
        WHERE d.external_game_id = a.external_game_id AND d.status = 'approved'
    )
ORDER BY a.external_game_id
`

type GamesMissingApprovedDescriptionRow struct {
	ExternalGameID int32  `json:"external_game_id"`
	Name           string `json:"name"`
}

// the run gate: distinct games present in a population that have no approved description yet.
func (q *Queries) GamesMissingApprovedDescription(ctx context.Context, populationID int32) ([]GamesMissingApprovedDescriptionRow, error) {
	rows, err := q.db.Query(ctx, gamesMissingApprovedDescription, populationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GamesMissingApprovedDescriptionRow{}
	for rows.Next() {
		var i GamesMissingApprovedDescriptionRow
		if err := rows.Scan(&i.ExternalGameID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameDescription = `-- name: GetGameDescription :one
SELECT id, external_game_id, version, status, profile, rendered_text, research_model, sources, valence_flags, error, content_hash, created_at, approved_by, approved_at FROM game_descriptions WHERE id = $1
`

func (q *Queries) GetGameDescription(ctx context.Context, id int32) (GameDescription, error) {
	row := q.db.QueryRow(ctx, getGameDescription, id)
	var i GameDescription
	err := row.Scan(
		&i.ID,
		&i.ExternalGameID,
		&i.Version,
		&i.Status,
		&i.Profile,
		&i.RenderedText,
		&i.ResearchModel,
		&i.Sources,
		&i.ValenceFlags,
		&i.Error,
		&i.ContentHash,
		&i.CreatedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
	)
	return i, err
}

const getLatestApprovedDescription = `-- name: GetLatestApprovedDescription :one
SELECT id, external_game_id, version, status, profile, rendered_text, research_model, sources, valence_flags, error, content_hash, created_at, approved_by, approved_at FROM game_descriptions
WHERE external_game_id = $1 AND status = 'approved'
`

func (q *Queries) GetLatestApprovedDescription(ctx context.Context, externalGameID int32) (GameDescription, error) {
	row := q.db.QueryRow(ctx, getLatestApprovedDescription, externalGameID)
	var i GameDescription
	err := row.Scan(
		&i.ID,
		&i.ExternalGameID,
		&i.Version,
		&i.Status,
		&i.Profile,
		&i.RenderedText,
		&i.ResearchModel,
		&i.Sources,
		&i.ValenceFlags,
		&i.Error,
		&i.ContentHash,
		&i.CreatedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
	)
	return i, err
}

const insertGameDescription = `-- name: InsertGameDescription :one
INSERT INTO game_descriptions (
    external_game_id, version, status, profile, rendered_text, research_model, sources, valence_flags, error
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, external_game_id, version, status, profile, rendered_text, research_model, sources, valence_flags, error, content_hash, created_at, approved_by, approved_at
`

type InsertGameDescriptionParams struct {
	ExternalGameID int32           `json:"external_game_id"`
	Version        int32           `json:"version"`
	Status         string          `json:"status"`
	Profile        json.RawMessage `json:"profile"`
	RenderedText   string          `json:"rendered_text"`
	ResearchModel  string          `json:"research_model"`
	Sources        json.RawMessage `json:"sources"`
	ValenceFlags   json.RawMessage `json:"valence_flags"`
	Error          string          `json:"error"`
}

// store a researched draft (or an invalid/error draft the reviewer must fix).
func (q *Queries) InsertGameDescription(ctx context.Context, arg InsertGameDescriptionParams) (GameDescription, error) {
	row := q.db.QueryRow(ctx, insertGameDescription,
		arg.ExternalGameID,
		arg.Version,
		arg.Status,
		arg.Profile,
		arg.RenderedText,
		arg.ResearchModel,
		arg.Sources,
		arg.ValenceFlags,
		arg.Error,
	)
	var i GameDescription
	err := row.Scan(
		&i.ID,
		&i.ExternalGameID,
		&i.Version,
		&i.Status,
		&i.Profile,
		&i.RenderedText,
		&i.ResearchModel,
		&i.Sources,
		&i.ValenceFlags,
		&i.Error,
		&i.ContentHash,
		&i.CreatedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
	)
	return i, err
}

const listGameDescriptionStates = `-- name: ListGameDescriptionStates :many
SELECT DISTINCT ON (external_game_id) external_game_id, status
FROM game_descriptions
ORDER BY external_game_id, version DESC
`

type ListGameDescriptionStatesRow struct {
	ExternalGameID int32  `json:"external_game_id"`
	Status         string `json:"status"`
}

// the latest version's status per game, for the games list badge.
func (q *Queries) ListGameDescriptionStates(ctx context.Context) ([]ListGameDescriptionStatesRow, error) {
	rows, err := q.db.Query(ctx, listGameDescriptionStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGameDescriptionStatesRow{}
	for rows.Next() {
		var i ListGameDescriptionStatesRow
		if err := rows.Scan(&i.ExternalGameID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameDescriptionsForGame = `-- name: ListGameDescriptionsForGame :many
SELECT id, external_game_id, version, status, profile, rendered_text, research_model, sources, valence_flags, error, content_hash, created_at, approved_by, approved_at FROM game_descriptions
WHERE external_game_id = $1
ORDER BY version DESC
`

// newest first; the review console lists the version history of one game.
func (q *Queries) ListGameDescriptionsForGame(ctx context.Context, externalGameID int32) ([]GameDescription, error) {
	rows, err := q.db.Query(ctx, listGameDescriptionsForGame, externalGameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GameDescription{}
	for rows.Next() {
		var i GameDescription
		if err := rows.Scan(
			&i.ID,
			&i.ExternalGameID,
			&i.Version,
			&i.Status,
			&i.Profile,
			&i.RenderedText,
			&i.ResearchModel,
			&i.Sources,
			&i.ValenceFlags,
			&i.Error,
			&i.ContentHash,
			&i.CreatedAt,
			&i.ApprovedBy,
			&i.ApprovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunGameDescriptions = `-- name: ListRunGameDescriptions :many
SELECT rgd.external_game_id, d.version, d.content_hash, d.rendered_text
FROM run_game_descriptions rgd
JOIN game_descriptions d ON d.id = rgd.game_description_id
WHERE rgd.run_id = $1
ORDER BY rgd.external_game_id
`

type ListRunGameDescriptionsRow struct {
	ExternalGameID int32  `json:"external_game_id"`
	Version        int32  `json:"version"`
	ContentHash    []byte `json:"content_hash"`
	RenderedText   string `json:"rendered_text"`
}

// the pinned descriptions for a run: game id, version, content hash, and the text to inject.
func (q *Queries) ListRunGameDescriptions(ctx context.Context, runID int32) ([]ListRunGameDescriptionsRow, error) {
	rows, err := q.db.Query(ctx, listRunGameDescriptions, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunGameDescriptionsRow{}
	for rows.Next() {
		var i ListRunGameDescriptionsRow
		if err := rows.Scan(
			&i.ExternalGameID,
			&i.Version,
			&i.ContentHash,
			&i.RenderedText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextDescriptionVersion = `-- name: NextDescriptionVersion :one
SELECT COALESCE(max(version), 0)::int + 1 AS version
FROM game_descriptions
WHERE external_game_id = $1
`

// the next version number for a games description chain (1 when it has none).
func (q *Queries) NextDescriptionVersion(ctx context.Context, externalGameID int32) (int32, error) {
	row := q.db.QueryRow(ctx, nextDescriptionVersion, externalGameID)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const pinRunGameDescriptions = `-- name: PinRunGameDescriptions :exec
INSERT INTO run_game_descriptions (run_id, external_game_id, game_description_id)
SELECT $1, a.external_game_id, d.id
FROM (
    SELECT DISTINCT a.external_game_id
    FROM individuals i
    JOIN artifacts a ON a.id = i.artifact_id
    WHERE i.population_id = $2
) a
JOIN game_descriptions d ON d.external_game_id = a.external_game_id AND d.status = 'approved'
ON CONFLICT (run_id, external_game_id) DO NOTHING
`

type PinRunGameDescriptionsParams struct {
	RunID        int32 `json:"run_id"`
	PopulationID int32 `json:"population_id"`
}

// freeze the approved description per game in the runs population onto the run.
func (q *Queries) PinRunGameDescriptions(ctx context.Context, arg PinRunGameDescriptionsParams) error {
	_, err := q.db.Exec(ctx, pinRunGameDescriptions, arg.RunID, arg.PopulationID)
	return err
}

const supersedePriorApproved = `-- name: SupersedePriorApproved :exec
UPDATE game_descriptions
SET status = 'superseded'
WHERE external_game_id = $1 AND status = 'approved'
`

// demote the current approved description for a game (called before approving a newer version).
func (q *Queries) SupersedePriorApproved(ctx context.Context, externalGameID int32) error {
	_, err := q.db.Exec(ctx, supersedePriorApproved, externalGameID)
	return err
}

const updateDraftDescription = `-- name: UpdateDraftDescription :one
UPDATE game_descriptions
SET profile = $2, rendered_text = $3, sources = $4, valence_flags = $5
WHERE id = $1 AND status = 'draft'
RETURNING id, external_game_id, version, status, profile, rendered_text, research_model, sources, valence_flags, error, content_hash, created_at, approved_by, approved_at
`

type UpdateDraftDescriptionParams struct {
	ID           int32           `json:"id"`
	Profile      json.RawMessage `json:"profile"`
	RenderedText string          `json:"rendered_text"`
	Sources      json.RawMessage `json:"sources"`
	ValenceFlags json.RawMessage `json:"valence_flags"`
}

// edit a draft in place: the reviewers fixes to the structured profile and the rendered text, plus the
// re-run valence flags. only drafts are editable.
func (q *Queries) UpdateDraftDescription(ctx context.Context, arg UpdateDraftDescriptionParams) (GameDescription, error) {
	row := q.db.QueryRow(ctx, updateDraftDescription,
		arg.ID,
		arg.Profile,
		arg.RenderedText,
		arg.Sources,
		arg.ValenceFlags,
	)
	var i GameDescription
	err := row.Scan(
		&i.ID,
		&i.ExternalGameID,
		&i.Version,
		&i.Status,
		&i.Profile,
		&i.RenderedText,
		&i.ResearchModel,
		&i.Sources,
		&i.ValenceFlags,
		&i.Error,
		&i.ContentHash,
		&i.CreatedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
	)
	return i, err
}
