// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Annotation struct {
	ID           int64              `json:"id"`
	RunID        int32              `json:"run_id"`
	IndividualID int64              `json:"individual_id"`
	AnnotatorID  int32              `json:"annotator_id"`
	Status       string             `json:"status"`
	RawResponse  []byte             `json:"raw_response"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type AnnotationPattern struct {
	ID           int64              `json:"id"`
	AnnotationID int64              `json:"annotation_id"`
	PatternID    int32              `json:"pattern_id"`
	Evidence     *string            `json:"evidence"`
	Explanation  *string            `json:"explanation"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Annotator struct {
	ID        int32              `json:"id"`
	Kind      string             `json:"kind"`
	ModelID   *int32             `json:"model_id"`
	Label     string             `json:"label"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Artifact struct {
	ID             int64              `json:"id"`
	Modality       string             `json:"modality"`
	Source         string             `json:"source"`
	SourceID       *string            `json:"source_id"`
	ContentHash    []byte             `json:"content_hash"`
	ScrapedAt      pgtype.Timestamptz `json:"scraped_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ExternalGameID int32              `json:"external_game_id"`
}

type ImageDetail struct {
	ArtifactID int64   `json:"artifact_id"`
	ImageUri   string  `json:"image_uri"`
	Width      *int32  `json:"width"`
	Height     *int32  `json:"height"`
	MimeType   *string `json:"mime_type"`
	OcrText    *string `json:"ocr_text"`
}

type Individual struct {
	ID           int64              `json:"id"`
	PopulationID int32              `json:"population_id"`
	ArtifactID   int64              `json:"artifact_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Model struct {
	ID         int32              `json:"id"`
	Family     string             `json:"family"`
	Slug       string             `json:"slug"`
	Name       string             `json:"name"`
	Modalities []string           `json:"modalities"`
	Active     bool               `json:"active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Population struct {
	ID              int32              `json:"id"`
	Modality        string             `json:"modality"`
	Description     *string            `json:"description"`
	Criteria        []byte             `json:"criteria"`
	ArtifactsCutoff pgtype.Timestamptz `json:"artifacts_cutoff"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Prompt struct {
	ID           int32              `json:"id"`
	Name         string             `json:"name"`
	Version      int32              `json:"version"`
	Modality     string             `json:"modality"`
	SystemPrompt *string            `json:"system_prompt"`
	Template     string             `json:"template"`
	ContentHash  []byte             `json:"content_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Run struct {
	ID           int32              `json:"id"`
	RunType      string             `json:"run_type"`
	PopulationID int32              `json:"population_id"`
	PromptID     int32              `json:"prompt_id"`
	Temperature  pgtype.Numeric     `json:"temperature"`
	TopP         pgtype.Numeric     `json:"top_p"`
	Params       []byte             `json:"params"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type ScrapeCursor struct {
	ExternalGameID int32              `json:"external_game_id"`
	Filter         string             `json:"filter"`
	Language       string             `json:"language"`
	Cursor         string             `json:"cursor"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type TaxonomyHighLevel struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Version     int32  `json:"version"`
	Active      bool   `json:"active"`
}

type TaxonomyMesoLevel struct {
	ID          int32  `json:"id"`
	ParentID    int32  `json:"parent_id"`
	Code        string `json:"code"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Version     int32  `json:"version"`
	Active      bool   `json:"active"`
}

type TextReviewDetail struct {
	ArtifactID        int64          `json:"artifact_id"`
	Body              string         `json:"body"`
	VotedUp           bool           `json:"voted_up"`
	HoursPlayed       int32          `json:"hours_played"`
	Lang              string         `json:"lang"`
	WeightedVoteScore pgtype.Numeric `json:"weighted_vote_score"`
}
