// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: models.sql

package db

import (
	"context"
)

const getModelBySlug = `-- name: GetModelBySlug :one
SELECT id, family, slug, name, modalities, active, created_at FROM models where slug = $1
`

func (q *Queries) GetModelBySlug(ctx context.Context, slug string) (Model, error) {
	row := q.db.QueryRow(ctx, getModelBySlug, slug)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.Family,
		&i.Slug,
		&i.Name,
		&i.Modalities,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveModels = `-- name: ListActiveModels :many
SELECT id, family, slug, name, modalities, active, created_at FROM models where active ORDER BY family, slug
`

func (q *Queries) ListActiveModels(ctx context.Context) ([]Model, error) {
	rows, err := q.db.Query(ctx, listActiveModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Model{}
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.Family,
			&i.Slug,
			&i.Name,
			&i.Modalities,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveModelsByModality = `-- name: ListActiveModelsByModality :many
SELECT id, family, slug, name, modalities, active, created_at
FROM models
WHERE active
    AND $1::varchar = ANY(modalities)
ORDER BY family
`

func (q *Queries) ListActiveModelsByModality(ctx context.Context, dollar_1 string) ([]Model, error) {
	rows, err := q.db.Query(ctx, listActiveModelsByModality, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Model{}
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.Family,
			&i.Slug,
			&i.Name,
			&i.Modalities,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertModel = `-- name: UpsertModel :one
INSERT INTO models (family, slug, name, modalities)
VALUES ($1, $2, $3, $4)
ON CONFLICT (slug) DO UPDATE
    SET family     = EXCLUDED.family,
        name       = EXCLUDED.name,
        modalities = EXCLUDED.modalities
RETURNING id
`

type UpsertModelParams struct {
	Family     string   `json:"family"`
	Slug       string   `json:"slug"`
	Name       string   `json:"name"`
	Modalities []string `json:"modalities"`
}

func (q *Queries) UpsertModel(ctx context.Context, arg UpsertModelParams) (int32, error) {
	row := q.db.QueryRow(ctx, upsertModel,
		arg.Family,
		arg.Slug,
		arg.Name,
		arg.Modalities,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
