// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prompts.sql

package db

import (
	"context"
)

const createPrompt = `-- name: CreatePrompt :one
INSERT INTO prompts (name, version, modality, system_prompt, template)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreatePromptParams struct {
	Name         string  `json:"name"`
	Version      int32   `json:"version"`
	Modality     string  `json:"modality"`
	SystemPrompt *string `json:"system_prompt"`
	Template     string  `json:"template"`
}

func (q *Queries) CreatePrompt(ctx context.Context, arg CreatePromptParams) (int32, error) {
	row := q.db.QueryRow(ctx, createPrompt,
		arg.Name,
		arg.Version,
		arg.Modality,
		arg.SystemPrompt,
		arg.Template,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getLatestPrompt = `-- name: GetLatestPrompt :one
SELECT id, name, version, modality, system_prompt, template, content_hash, created_at FROM prompts WHERE name = $1 ORDER BY version DESC LIMIT 1
`

func (q *Queries) GetLatestPrompt(ctx context.Context, name string) (Prompt, error) {
	row := q.db.QueryRow(ctx, getLatestPrompt, name)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Modality,
		&i.SystemPrompt,
		&i.Template,
		&i.ContentHash,
		&i.CreatedAt,
	)
	return i, err
}

const getPrompt = `-- name: GetPrompt :one
SELECT id, name, version, modality, system_prompt, template, content_hash, created_at FROM prompts WHERE id = $1
`

func (q *Queries) GetPrompt(ctx context.Context, id int32) (Prompt, error) {
	row := q.db.QueryRow(ctx, getPrompt, id)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Modality,
		&i.SystemPrompt,
		&i.Template,
		&i.ContentHash,
		&i.CreatedAt,
	)
	return i, err
}

const getPromptByNameVersion = `-- name: GetPromptByNameVersion :one
SELECT id, name, version, modality, system_prompt, template, content_hash, created_at FROM prompts where name = $1 AND version = $2
`

type GetPromptByNameVersionParams struct {
	Name    string `json:"name"`
	Version int32  `json:"version"`
}

func (q *Queries) GetPromptByNameVersion(ctx context.Context, arg GetPromptByNameVersionParams) (Prompt, error) {
	row := q.db.QueryRow(ctx, getPromptByNameVersion, arg.Name, arg.Version)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Modality,
		&i.SystemPrompt,
		&i.Template,
		&i.ContentHash,
		&i.CreatedAt,
	)
	return i, err
}
