// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provenance.sql

package db

import (
	"context"
	"encoding/json"
)

const listRunAnnotators = `-- name: ListRunAnnotators :many
SELECT annotator_id, provider, model_slug, client_version, sampling
FROM run_annotators
WHERE run_id = $1
ORDER BY annotator_id
`

type ListRunAnnotatorsRow struct {
	AnnotatorID   int32           `json:"annotator_id"`
	Provider      string          `json:"provider"`
	ModelSlug     string          `json:"model_slug"`
	ClientVersion string          `json:"client_version"`
	Sampling      json.RawMessage `json:"sampling"`
}

// read the frozen panel.
func (q *Queries) ListRunAnnotators(ctx context.Context, runID int32) ([]ListRunAnnotatorsRow, error) {
	rows, err := q.db.Query(ctx, listRunAnnotators, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunAnnotatorsRow{}
	for rows.Next() {
		var i ListRunAnnotatorsRow
		if err := rows.Scan(
			&i.AnnotatorID,
			&i.Provider,
			&i.ModelSlug,
			&i.ClientVersion,
			&i.Sampling,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRunConfigDigest = `-- name: SetRunConfigDigest :exec
UPDATE runs SET config_digest = $2 WHERE id = $1 AND config_digest IS NULL
`

type SetRunConfigDigestParams struct {
	ID           int32   `json:"id"`
	ConfigDigest *string `json:"config_digest"`
}

// stamp the digest once. a second snapshot is a no-op
func (q *Queries) SetRunConfigDigest(ctx context.Context, arg SetRunConfigDigestParams) error {
	_, err := q.db.Exec(ctx, setRunConfigDigest, arg.ID, arg.ConfigDigest)
	return err
}

const snapshotRunAnnotator = `-- name: SnapshotRunAnnotator :exec
INSERT INTO run_annotators (run_id, annotator_id, provider, model_slug, client_version, sampling)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (run_id, annotator_id) DO NOTHING
`

type SnapshotRunAnnotatorParams struct {
	RunID         int32           `json:"run_id"`
	AnnotatorID   int32           `json:"annotator_id"`
	Provider      string          `json:"provider"`
	ModelSlug     string          `json:"model_slug"`
	ClientVersion string          `json:"client_version"`
	Sampling      json.RawMessage `json:"sampling"`
}

// freeze one panel member
func (q *Queries) SnapshotRunAnnotator(ctx context.Context, arg SnapshotRunAnnotatorParams) error {
	_, err := q.db.Exec(ctx, snapshotRunAnnotator,
		arg.RunID,
		arg.AnnotatorID,
		arg.Provider,
		arg.ModelSlug,
		arg.ClientVersion,
		arg.Sampling,
	)
	return err
}
