// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addIndividual = `-- name: AddIndividual :exec
INSERT INTO individuals (population_id, artifact_id)
VALUES ($1, $2)
ON CONFLICT (population_id, artifact_id) DO NOTHING
`

type AddIndividualParams struct {
	PopulationID int32 `json:"population_id"`
	ArtifactID   int64 `json:"artifact_id"`
}

func (q *Queries) AddIndividual(ctx context.Context, arg AddIndividualParams) error {
	_, err := q.db.Exec(ctx, addIndividual, arg.PopulationID, arg.ArtifactID)
	return err
}

const listUnannotatedTextReviews = `-- name: ListUnannotatedTextReviews :many
SELECT
    i.id as population_item_id,
    a.id as artifact_id,
    trd.body
FROM runs r
JOIN individuals i ON i.population_id = r.population_id
JOIN artifacts a ON a.id = i.artifact_id
JOIN text_review_details trd ON trd.artifact_id = a.id
WHERE r.id = $1
    AND NOT EXISTS (
        SELECT 1 FROM annotations an
        WHERE an.run_id = r.id
            AND an.individual_id = i.id
            AND an.annotator_id = $2
            AND an.status = 'completed'
    )
ORDER BY i.id
LIMIT $3
`

type ListUnannotatedTextReviewsParams struct {
	ID          int32 `json:"id"`
	AnnotatorID int32 `json:"annotator_id"`
	Limit       int32 `json:"limit"`
}

type ListUnannotatedTextReviewsRow struct {
	PopulationItemID int64  `json:"population_item_id"`
	ArtifactID       int64  `json:"artifact_id"`
	Body             string `json:"body"`
}

// The annotation worker's queue: items in the run's population not yet successfully annotated by an annotator
func (q *Queries) ListUnannotatedTextReviews(ctx context.Context, arg ListUnannotatedTextReviewsParams) ([]ListUnannotatedTextReviewsRow, error) {
	rows, err := q.db.Query(ctx, listUnannotatedTextReviews, arg.ID, arg.AnnotatorID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnannotatedTextReviewsRow{}
	for rows.Next() {
		var i ListUnannotatedTextReviewsRow
		if err := rows.Scan(&i.PopulationItemID, &i.ArtifactID, &i.Body); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAnnotation = `-- name: UpsertAnnotation :one
INSERT INTO annotations (run_id, individual_id, annotator_id, status, raw_response)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (run_id, individual_id, annotator_id) DO UPDATE
    SET status = EXCLUDED.status,
        raw_response = EXCLUDED.raw_response
    WHERE annotations.status <> 'completed'
RETURNING id
`

type UpsertAnnotationParams struct {
	RunID        int32  `json:"run_id"`
	IndividualID int64  `json:"individual_id"`
	AnnotatorID  int32  `json:"annotator_id"`
	Status       string `json:"status"`
	RawResponse  []byte `json:"raw_response"`
}

// Idempotent. The WHERE guard means an already completed annotation is not touched
// Returning yields no rows in this case, and the worker treats it as already done
func (q *Queries) UpsertAnnotation(ctx context.Context, arg UpsertAnnotationParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertAnnotation,
		arg.RunID,
		arg.IndividualID,
		arg.AnnotatorID,
		arg.Status,
		arg.RawResponse,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertArtifact = `-- name: UpsertArtifact :one
INSERT INTO artifacts (modality, source, source_id, content_hash, scraped_at, external_game_id)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (source, source_id) DO UPDATE
    SET scraped_at = EXCLUDED.scraped_at
RETURNING id
`

type UpsertArtifactParams struct {
	Modality       string             `json:"modality"`
	Source         string             `json:"source"`
	SourceID       *string            `json:"source_id"`
	ContentHash    []byte             `json:"content_hash"`
	ScrapedAt      pgtype.Timestamptz `json:"scraped_at"`
	ExternalGameID int32              `json:"external_game_id"`
}

// Idempotent on source_id; DO UPDATE instead of DO NOTHING because we want it to always return the id even on re-scrape.
// ON CONFLICT we update the scraped_at date.
func (q *Queries) UpsertArtifact(ctx context.Context, arg UpsertArtifactParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertArtifact,
		arg.Modality,
		arg.Source,
		arg.SourceID,
		arg.ContentHash,
		arg.ScrapedAt,
		arg.ExternalGameID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertTextReviewDetail = `-- name: UpsertTextReviewDetail :exec
INSERT INTO text_review_details (artifact_id, body, voted_up, hours_played, lang, weighted_vote_score)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (artifact_id) DO UPDATE
    SET voted_up = EXCLUDED.voted_up,
        hours_played = EXCLUDED.hours_played
`

type UpsertTextReviewDetailParams struct {
	ArtifactID        int64          `json:"artifact_id"`
	Body              string         `json:"body"`
	VotedUp           bool           `json:"voted_up"`
	HoursPlayed       int32          `json:"hours_played"`
	Lang              string         `json:"lang"`
	WeightedVoteScore pgtype.Numeric `json:"weighted_vote_score"`
}

// On re-scrape we only refresh the volatile signal (votes, hours).
// body, lang and score stay as first seen on purpose, so annotation always line up with the text they ran on.
// An edited review is a new artifact if we ever want to recapture it.
func (q *Queries) UpsertTextReviewDetail(ctx context.Context, arg UpsertTextReviewDetailParams) error {
	_, err := q.db.Exec(ctx, upsertTextReviewDetail,
		arg.ArtifactID,
		arg.Body,
		arg.VotedUp,
		arg.HoursPlayed,
		arg.Lang,
		arg.WeightedVoteScore,
	)
	return err
}
