// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	AddIndividual(ctx context.Context, arg AddIndividualParams) error
	// gold run: how many patterns are decided per review, to show progress on the worklist.
	CountAdjudicationsPerReview(ctx context.Context, runID int32) ([]CountAdjudicationsPerReviewRow, error)
	CountArtifactsBySource(ctx context.Context, arg CountArtifactsBySourceParams) (int64, error)
	// How many panel members completed this review (the denominator for every pattern's vote).
	CountCompletedRaters(ctx context.Context, arg CountCompletedRatersParams) (int32, error)
	CountIndividuals(ctx context.Context, populationID int32) (int64, error)
	CreateAnnotator(ctx context.Context, arg CreateAnnotatorParams) (int32, error)
	CreatePopulation(ctx context.Context, arg CreatePopulationParams) (int32, error)
	CreatePrompt(ctx context.Context, arg CreatePromptParams) (int32, error)
	CreateRun(ctx context.Context, arg CreateRunParams) (int32, error)
	// Clear prior pattern rows before re-writing, so a retry doesn't leave stale ones.
	DeleteAnnotationPatterns(ctx context.Context, annotationID int64) error
	FreezeStratifiedPopulation(ctx context.Context, arg FreezeStratifiedPopulationParams) (int64, error)
	GetAnnotatorByLabel(ctx context.Context, label string) (Annotator, error)
	GetArtifact(ctx context.Context, id int64) (Artifact, error)
	GetLLMAnnotatorByModel(ctx context.Context, modelID *int32) (Annotator, error)
	GetLatestPrompt(ctx context.Context, name string) (Prompt, error)
	GetMesoPatternCodes(ctx context.Context, version int32) ([]GetMesoPatternCodesRow, error)
	GetModelBySlug(ctx context.Context, slug string) (Model, error)
	// The panel's verdict for one (run, individual, pattern)
	GetPanelVoteForCell(ctx context.Context, arg GetPanelVoteForCellParams) (GetPanelVoteForCellRow, error)
	GetPrompt(ctx context.Context, id int32) (Prompt, error)
	GetPromptByNameVersion(ctx context.Context, arg GetPromptByNameVersionParams) (Prompt, error)
	// The review body to render for the auditor
	GetReviewText(ctx context.Context, individualID int64) (string, error)
	GetRun(ctx context.Context, id int32) (Run, error)
	GetScrapeCursor(ctx context.Context, arg GetScrapeCursorParams) (string, error)
	// text-specific query
	GetTextReviewForIndividual(ctx context.Context, id int64) (GetTextReviewForIndividualRow, error)
	InsertAnnotationPattern(ctx context.Context, arg InsertAnnotationPatternParams) error
	ListActiveModels(ctx context.Context) ([]Model, error)
	ListActiveModelsByModality(ctx context.Context, dollar_1 string) ([]Model, error)
	ListAnnotators(ctx context.Context) ([]Annotator, error)
	// gold run
	ListDedicedCells(ctx context.Context, runID int32) ([]ListDedicedCellsRow, error)
	// The taxonomy as of a pinned version
	ListMesoPatternsByVersion(ctx context.Context, version int32) ([]ListMesoPatternsByVersionRow, error)
	// Per-rater verdicts with each model's own evidence and explanation
	ListPanelVotesForCell(ctx context.Context, arg ListPanelVotesForCellParams) ([]ListPanelVotesForCellRow, error)
	// Existing gold labels for one review, to pre-fill the checkboxes on revisit.
	ListReviewAdjudications(ctx context.Context, arg ListReviewAdjudicationsParams) ([]ListReviewAdjudicationsRow, error)
	// Every panel member's detection for one review, across all patterns: who flagged what, with their
	// evidence and explanation. annotation_patterns holds positives only, so a row means that model
	// detected that pattern on this review.
	ListReviewDetections(ctx context.Context, arg ListReviewDetectionsParams) ([]ListReviewDetectionsRow, error)
	// Read the frozen panel.
	ListRunAnnotators(ctx context.Context, runID int32) ([]ListRunAnnotatorsRow, error)
	ListRunsByPopulation(ctx context.Context, populationID int32) ([]Run, error)
	// The full MESO codebook for a version: code, name, definition, and the family it sits under.
	ListTaxonomy(ctx context.Context, version int32) ([]ListTaxonomyRow, error)
	// The annotation worker's queue: items in the run's population not yet successfully annotated by an annotator
	ListUnannotatedTextReviews(ctx context.Context, arg ListUnannotatedTextReviewsParams) ([]ListUnannotatedTextReviewsRow, error)
	// The work queue for one panel member.
	// Modality agnostic
	ListUnnanotatedIndividuals(ctx context.Context, arg ListUnnanotatedIndividualsParams) ([]int64, error)
	// Fixed N individuals per game from the population, ordered deterministically
	// Always yields the same subset.
	// Drops any review where a panel member didn't 'complete' (>=1 parse_error) for the panel run
	SampleStratifiedIndividuals(ctx context.Context, arg SampleStratifiedIndividualsParams) ([]SampleStratifiedIndividualsRow, error)
	// Representative selection with common filters and the cutoff
	// Criteria need dynamic SQL
	SelectTextReviewsFromPopulation(ctx context.Context, arg SelectTextReviewsFromPopulationParams) ([]SelectTextReviewsFromPopulationRow, error)
	// Stamp the digest once. A second snapshot is a no-op
	SetRunConfigDigest(ctx context.Context, arg SetRunConfigDigestParams) error
	// Freeze one panel member
	SnapshotRunAnnotator(ctx context.Context, arg SnapshotRunAnnotatorParams) error
	// Re-saving a review updates the decision (the auditor is deliberately changing it) and re-freezes
	// the panel seed at the new decision time.
	UpsertAdjudication(ctx context.Context, arg UpsertAdjudicationParams) error
	// Idempotent. The WHERE guard means an already completed annotation is not touched
	// Returning yields no rows in this case, and the worker treats it as already done
	UpsertAnnotation(ctx context.Context, arg UpsertAnnotationParams) (int64, error)
	// Idempotent on source_id; DO UPDATE instead of DO NOTHING because we want it to always return the id even on re-scrape.
	// ON CONFLICT we update the scraped_at date.
	UpsertArtifact(ctx context.Context, arg UpsertArtifactParams) (int64, error)
	UpsertModel(ctx context.Context, arg UpsertModelParams) (int32, error)
	UpsertScrapeCursor(ctx context.Context, arg UpsertScrapeCursorParams) error
	// On re-scrape we only refresh the volatile signal (votes, hours).
	// body, lang and score stay as first seen on purpose, so annotation always line up with the text they ran on.
	// An edited review is a new artifact if we ever want to recapture it.
	UpsertTextReviewDetail(ctx context.Context, arg UpsertTextReviewDetailParams) error
}

var _ Querier = (*Queries)(nil)
