// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	AddIndividual(ctx context.Context, arg AddIndividualParams) error
	// freeze a draft as the approved version. blocked unless it is a draft with no unresolved valence flags.
	ApproveDescription(ctx context.Context, arg ApproveDescriptionParams) (GameDescription, error)
	// the candidate pool for a sample: every completed review in the population, tagged with its stratum.
	// a review is classified by the panels per-pattern votes: flagged_majority if any pattern reached a
	// majority Present (n_present*2 > n_total), else flagged_split if any pattern had Present votes without
	// a majority (the panel disagreed), else silent (no pattern got a single Present vote).
	ClassifyReviewsForSampling(ctx context.Context, arg ClassifyReviewsForSamplingParams) ([]ClassifyReviewsForSamplingRow, error)
	// per shared model (in both panels), how many flagged patterns both runs agreed on vs flipped, across
	// the shared reviews. the universe is the union of present-cells for that model; mutual absence is not
	// counted. keyed by the meso code so it is stable across taxonomy versions.
	ComparisonModelAgreement(ctx context.Context, arg ComparisonModelAgreementParams) ([]ComparisonModelAgreementRow, error)
	// the worklist: every review both runs annotated, with how many patterns the two panels disagreed on.
	// this works for any two runs (same or different panels): each panel's verdict on a pattern is whether a
	// strict majority of its completed members flagged it; a flip is a pattern one panel's majority flagged
	// and the other's did not. patterns are keyed by meso code (stable across taxonomy versions). the
	// per-model detail lives in the drill-down.
	ComparisonReviewDivergence(ctx context.Context, arg ComparisonReviewDivergenceParams) ([]ComparisonReviewDivergenceRow, error)
	// gold run: how many patterns are decided per review, to show progress on the worklist.
	CountAdjudicationsPerReview(ctx context.Context, runID int32) ([]CountAdjudicationsPerReviewRow, error)
	CountAnnotatorRefs(ctx context.Context, annotatorID int32) (int32, error)
	CountArtifactsBySource(ctx context.Context, arg CountArtifactsBySourceParams) (int64, error)
	CountArtifactsForGame(ctx context.Context, externalGameID int32) (int32, error)
	// how many panel members completed this review (the denominator for every patterns vote).
	CountCompletedRaters(ctx context.Context, arg CountCompletedRatersParams) (int32, error)
	CountIndividuals(ctx context.Context, populationID int32) (int64, error)
	// curated individuals (reviews in a population) per game, across every population.
	CountIndividualsPerGame(ctx context.Context) ([]CountIndividualsPerGameRow, error)
	CountRunsForPrompt(ctx context.Context, promptID int32) (int32, error)
	CreateAnnotator(ctx context.Context, arg CreateAnnotatorParams) (int32, error)
	CreatePopulation(ctx context.Context, arg CreatePopulationParams) (int32, error)
	CreatePrompt(ctx context.Context, arg CreatePromptParams) (int32, error)
	CreateRun(ctx context.Context, arg CreateRunParams) (int32, error)
	// sample items cascade on the sample delete.
	DeleteAdjudicationSamplesByRun(ctx context.Context, panelRunID int32) error
	DeleteAdjudicationsByRun(ctx context.Context, runID int32) error
	// clear prior pattern rows before re-writing, so a retry doesnt leave stale ones.
	DeleteAnnotationPatterns(ctx context.Context, annotationID int64) error
	DeleteAnnotationPatternsByRun(ctx context.Context, runID int32) error
	DeleteAnnotationsByRun(ctx context.Context, runID int32) error
	DeleteAnnotator(ctx context.Context, id int32) error
	DeleteComparison(ctx context.Context, id int32) error
	DeleteGameDisplay(ctx context.Context, externalGameID int32) error
	DeleteIndividualsByPopulation(ctx context.Context, populationID int32) error
	DeletePopulation(ctx context.Context, id int32) error
	DeletePrompt(ctx context.Context, id int32) error
	// run_annotators cascade on the run delete.
	DeleteRun(ctx context.Context, id int32) error
	FreezeImagePopulation(ctx context.Context, arg FreezeImagePopulationParams) (int64, error)
	// a multimodal artifact has both channels, so this joins both detail tables: only artifacts with a body
	// and an image are frozen.
	FreezeMultimodalPopulation(ctx context.Context, arg FreezeMultimodalPopulationParams) (int64, error)
	FreezeStratifiedPopulation(ctx context.Context, arg FreezeStratifiedPopulationParams) (int64, error)
	// artifacts per game, the delete guard: a game with any artifact is frozen.
	GameArtifactTotals(ctx context.Context) ([]GameArtifactTotalsRow, error)
	GameReviewTotals(ctx context.Context) ([]GameReviewTotalsRow, error)
	// the run gate: distinct games present in a population that have no approved description yet.
	GamesMissingApprovedDescription(ctx context.Context, populationID int32) ([]GamesMissingApprovedDescriptionRow, error)
	GetAnnotatorByLabel(ctx context.Context, label string) (Annotator, error)
	GetArtifact(ctx context.Context, id int64) (Artifact, error)
	GetComparison(ctx context.Context, id int32) (Comparison, error)
	GetGameDescription(ctx context.Context, id int32) (GameDescription, error)
	GetGameDisplay(ctx context.Context, externalGameID int32) (GameDisplay, error)
	// the scrape handle a game registered for one source (e.g. its subreddit for 'reddit'). empty when the
	// game has no binding for that source.
	GetGameSourceRef(ctx context.Context, arg GetGameSourceRefParams) (string, error)
	// the most recent gold run for a population. adjudication samples and decisions write into one gold
	// run per population; pick the newest so a freshly drawn sample lands on the run the auditor reads.
	GetGoldRunForPopulation(ctx context.Context, populationID int32) (int32, error)
	GetImageForIndividual(ctx context.Context, id int64) (GetImageForIndividualRow, error)
	GetLLMAnnotatorByModel(ctx context.Context, modelID *int32) (Annotator, error)
	GetLatestApprovedDescription(ctx context.Context, externalGameID int32) (GameDescription, error)
	GetLatestPrompt(ctx context.Context, name string) (Prompt, error)
	// the most recent sample drawn for a panel run, to reopen its queue.
	GetLatestSampleForRun(ctx context.Context, panelRunID int32) (AdjudicationSample, error)
	GetMesoPatternCodes(ctx context.Context, version int32) ([]GetMesoPatternCodesRow, error)
	GetModelBySlug(ctx context.Context, slug string) (Model, error)
	// a multimodal item carries both channels: a text body and an image. inner-joining both detail tables
	// means it only returns artifacts that actually have both, which is exactly the multimodal case.
	GetMultimodalForIndividual(ctx context.Context, id int64) (GetMultimodalForIndividualRow, error)
	// the llm panel run whose votes seed a decision on this review. one panel per population; pick the
	// most recent so the frozen seed reflects the panel the auditor is actually looking at.
	GetPanelRunForReview(ctx context.Context, individualID int64) (int32, error)
	// the panels verdict for one (run, individual, pattern)
	GetPanelVoteForCell(ctx context.Context, arg GetPanelVoteForCellParams) (GetPanelVoteForCellRow, error)
	// resolve a meso pattern code (e.g. 'PM-1') the frontend sends to its row id, within a taxonomy
	// version. code is unique only per (code, version), so the version is required or the wrong versions
	// id comes back — which would make a saved adjudication unreadable against the runs actual taxonomy.
	GetPatternIDByCode(ctx context.Context, arg GetPatternIDByCodeParams) (int32, error)
	// one population row by id, for the population/run detail headers (modality, description, created_at).
	GetPopulation(ctx context.Context, id int32) (GetPopulationRow, error)
	GetPrompt(ctx context.Context, id int32) (Prompt, error)
	GetPromptByNameVersion(ctx context.Context, arg GetPromptByNameVersionParams) (Prompt, error)
	// the review header for the auditor/blind views
	GetReviewMeta(ctx context.Context, individualID int64) (GetReviewMetaRow, error)
	// the review body to render for the auditor
	GetReviewText(ctx context.Context, individualID int64) (string, error)
	GetRun(ctx context.Context, id int32) (Run, error)
	GetScrapeCursor(ctx context.Context, arg GetScrapeCursorParams) (string, error)
	// text-specific query. body, lang, and the game it belongs to (for description context).
	GetTextReviewForIndividual(ctx context.Context, id int64) (GetTextReviewForIndividualRow, error)
	// the sample header. params holds the per-stratum target Ns; seed is stored so the draw is auditable.
	InsertAdjudicationSample(ctx context.Context, arg InsertAdjudicationSampleParams) (int64, error)
	// one frozen member of a sample: its stratum and its inverse-probability weight (drawn / stratum_size).
	InsertAdjudicationSampleItem(ctx context.Context, arg InsertAdjudicationSampleItemParams) error
	InsertAnnotationPattern(ctx context.Context, arg InsertAnnotationPatternParams) error
	InsertComparison(ctx context.Context, arg InsertComparisonParams) (Comparison, error)
	// store a researched draft (or an invalid/error draft the reviewer must fix).
	InsertGameDescription(ctx context.Context, arg InsertGameDescriptionParams) (GameDescription, error)
	// register a game so it appears on the dashboard list and can be scraped. external_game_id is left to
	// the sequence (a high internal id), source_refs holds the per-source scrape handles.
	InsertGameDisplay(ctx context.Context, arg InsertGameDisplayParams) (GameDisplay, error)
	ListActiveModels(ctx context.Context) ([]Model, error)
	ListActiveModelsByModality(ctx context.Context, dollar_1 string) ([]Model, error)
	ListAnnotators(ctx context.Context) ([]Annotator, error)
	ListAnnotatorsByIDs(ctx context.Context, ids []int32) ([]Annotator, error)
	// every annotator as a form option, carrying the display model name for llm annotators (NULL for
	// humans). ListAnnotators returns the raw rows with only a model_id; this resolves the name in SQL so
	// the API never has to look models up one by one.
	ListAnnotatorsWithModel(ctx context.Context) ([]ListAnnotatorsWithModelRow, error)
	ListComparisons(ctx context.Context) ([]Comparison, error)
	// gold run
	ListDedicedCells(ctx context.Context, runID int32) ([]ListDedicedCellsRow, error)
	// the latest version's status per game, for the games list badge.
	ListGameDescriptionStates(ctx context.Context) ([]ListGameDescriptionStatesRow, error)
	// newest first; the review console lists the version history of one game.
	ListGameDescriptionsForGame(ctx context.Context, externalGameID int32) ([]GameDescription, error)
	// the curated games with their presentation metadata and per-source handles. external_game_id is the
	// stable internal id the frontend uses as `gameId`; source_refs maps each source to its scrape handle.
	ListGameDisplays(ctx context.Context) ([]GameDisplay, error)
	// the strategic-intent parents used by a pinned meso version
	ListHighLevelsForMesoVersion(ctx context.Context, version int32) ([]ListHighLevelsForMesoVersionRow, error)
	// the active LLM panel fetch from the DB with each annotator with its model slug
	ListLLMAnnotators(ctx context.Context) ([]ListLLMAnnotatorsRow, error)
	// the panel members of a run: every annotator referenced by runs.annotator_ids, with the kind
	// (llm | human) and a display label. LLM members carry their model name, humans their own label.
	ListMembersForRun(ctx context.Context, runID int32) ([]ListMembersForRunRow, error)
	// the taxonomy as of a pinned version
	ListMesoPatternsByVersion(ctx context.Context, version int32) ([]ListMesoPatternsByVersionRow, error)
	// per-rater verdicts with each models own evidence and explanation
	ListPanelVotesForCell(ctx context.Context, arg ListPanelVotesForCellParams) ([]ListPanelVotesForCellRow, error)
	// every population with its size (the number of frozen individuals). LEFT JOIN so an empty population
	// still appears with a zero count. newest first, the order an operator picking a population wants.
	ListPopulations(ctx context.Context) ([]ListPopulationsRow, error)
	// the populations that contain this games reviews, each with the games slice: how many of the
	// games individuals fall in the population, and how many of those have a completed annotation. a
	// population is multi-game (stratified, per-game capped), so this is THIS games part of it. counts
	// are per population, never summed across them.
	ListPopulationsForGame(ctx context.Context, externalGameID int32) ([]ListPopulationsForGameRow, error)
	// every prompt as a form option: its id, name, version and modality, plus how many runs use it (a
	// prompt with runs is frozen). ordered by id for a stable list.
	ListPrompts(ctx context.Context) ([]ListPromptsRow, error)
	// existing gold labels for one review in one pass, to pre-fill the checkboxes on revisit. the blind
	// read asks for pass='blind' so it never sees the open-pass labels, and the other way round.
	ListReviewAdjudications(ctx context.Context, arg ListReviewAdjudicationsParams) ([]ListReviewAdjudicationsRow, error)
	// every panel members detection for one review, across all patterns: who flagged what, with their
	// evidence and explanation. annotation_patterns holds positives only, so a row means that model
	// detected that pattern on this review.
	ListReviewDetections(ctx context.Context, arg ListReviewDetectionsParams) ([]ListReviewDetectionsRow, error)
	// read the frozen panel.
	ListRunAnnotators(ctx context.Context, runID int32) ([]ListRunAnnotatorsRow, error)
	// the pinned descriptions for a run: game id, version, content hash, and the text to inject.
	ListRunGameDescriptions(ctx context.Context, runID int32) ([]ListRunGameDescriptionsRow, error)
	ListRunIDsByPopulation(ctx context.Context, populationID int32) ([]int32, error)
	// every run with what an operator needs to recognise and pick it: its type, the population modality as a
	// label, the foreign keys, the taxonomy version, when it ran, and the size of the panel it pinned.
	ListRuns(ctx context.Context) ([]ListRunsRow, error)
	ListRunsByPopulation(ctx context.Context, populationID int32) ([]Run, error)
	// one row per run with its populations modality as a human label and its creation time.
	// annotator_ids is the panel the run pinned; members are resolved separately per run.
	ListRunsForDashboard(ctx context.Context) ([]ListRunsForDashboardRow, error)
	// the queue for a sample
	ListSampleReviews(ctx context.Context, arg ListSampleReviewsParams) ([]ListSampleReviewsRow, error)
	// the full MESO codebook for a version: code, name, definition, and the family it sits under.
	ListTaxonomy(ctx context.Context, version int32) ([]ListTaxonomyRow, error)
	// the annotation workers queue: items in the runs population not yet successfully annotated by an annotator
	ListUnannotatedTextReviews(ctx context.Context, arg ListUnannotatedTextReviewsParams) ([]ListUnannotatedTextReviewsRow, error)
	// the work queue for one panel member.
	// modality agnostic
	ListUnnanotatedIndividuals(ctx context.Context, arg ListUnnanotatedIndividualsParams) ([]int64, error)
	// per LLM model, the number of DISTINCT reviews of one game annotated within one population. counting
	// distinct individuals (not annotation rows) and scoping to a single population makes the models
	// comparable: inside one population they all share the same work set, so a complete run shows every
	// model at the populations slice size, not a runaway sum across runs.
	ModelStatsForGamePopulation(ctx context.Context, arg ModelStatsForGamePopulationParams) ([]ModelStatsForGamePopulationRow, error)
	ModelStatsForGameRun(ctx context.Context, arg ModelStatsForGameRunParams) ([]ModelStatsForGameRunRow, error)
	// the next version number for a games description chain (1 when it has none).
	NextDescriptionVersion(ctx context.Context, externalGameID int32) (int32, error)
	// the panel that worked a population: every annotator frozen onto any of the populations runs, with
	// its kind (llm | human) and a display label (the model name for an llm, the annotators own label
	// for a human). run_annotators is the single source of "who annotates this run".
	PanelForPopulation(ctx context.Context, populationID int32) ([]PanelForPopulationRow, error)
	// freeze the approved description per game in the runs population onto the run.
	PinRunGameDescriptions(ctx context.Context, arg PinRunGameDescriptionsParams) error
	// the blast radius of deleting a population: its individuals, the runs over it, and those runs
	// annotations and adjudication samples.
	PopulationImpact(ctx context.Context, populationID int32) (PopulationImpactRow, error)
	// for one population, its per-game slice: how many of the populations reviews belong to each game and
	// how many of those have a completed annotation. mirrors ListPopulationsForGame but pivots to group by
	// game within a single population instead of by population within a single game.
	PopulationPerGame(ctx context.Context, populationID int32) ([]PopulationPerGameRow, error)
	ReviewStatsPerGame(ctx context.Context) ([]ReviewStatsPerGameRow, error)
	// the blast radius of deleting a run: its annotations, the adjudication samples it seeds (as panel or
	// gold), and its adjudications.
	RunImpact(ctx context.Context, runID int32) (RunImpactRow, error)
	// fixed N individuals per game from the population, ordered deterministically
	// always yields the same subset.
	// drops any review where a panel member didnt 'complete' (>=1 parse_error) for the panel run
	SampleStratifiedIndividuals(ctx context.Context, arg SampleStratifiedIndividualsParams) ([]SampleStratifiedIndividualsRow, error)
	// representative selection with common filters and the cutoff
	// criteria need dynamic SQL
	SelectTextReviewsFromPopulation(ctx context.Context, arg SelectTextReviewsFromPopulationParams) ([]SelectTextReviewsFromPopulationRow, error)
	// stamp the digest once. a second snapshot is a no-op
	SetRunConfigDigest(ctx context.Context, arg SetRunConfigDigestParams) error
	// freeze one panel member
	SnapshotRunAnnotator(ctx context.Context, arg SnapshotRunAnnotatorParams) error
	// demote the current approved description for a game (called before approving a newer version).
	SupersedePriorApproved(ctx context.Context, externalGameID int32) error
	UpdateAnnotatorLabel(ctx context.Context, arg UpdateAnnotatorLabelParams) error
	// edit a draft in place: the reviewers fixes to the structured profile and the rendered text, plus the
	// re-run valence flags. only drafts are editable.
	UpdateDraftDescription(ctx context.Context, arg UpdateDraftDescriptionParams) (GameDescription, error)
	// edit a games display fields and its per-source handles.
	UpdateGameDisplay(ctx context.Context, arg UpdateGameDisplayParams) (GameDisplay, error)
	UpdatePrompt(ctx context.Context, arg UpdatePromptParams) error
	// re-saving a review updates the decision (the auditor is deliberately changing it) and re-freezes
	// the panel seed at the new decision time. pass keeps the open and blind labels for a cell apart, so
	// saving one never touches the other.
	UpsertAdjudication(ctx context.Context, arg UpsertAdjudicationParams) error
	// idempotent. the WHERE guard means an already completed annotation is not touched
	// returning yields no rows in this case, and the worker treats it as already done
	UpsertAnnotation(ctx context.Context, arg UpsertAnnotationParams) (int64, error)
	// idempotent on source_id; DO UPDATE because we want it to always return the id even on re-scrape.
	// ON CONFLICT we update the scraped_at date.
	UpsertArtifact(ctx context.Context, arg UpsertArtifactParams) (int64, error)
	UpsertImageDetail(ctx context.Context, arg UpsertImageDetailParams) error
	UpsertModel(ctx context.Context, arg UpsertModelParams) (int32, error)
	UpsertScrapeCursor(ctx context.Context, arg UpsertScrapeCursorParams) error
	// text channel: body and lang are universal, source_meta holds everything source-specific
	// (Steam voted_up/hours/score, Reddit subreddit/post_id). on re-scrape we refresh source_meta.
	UpsertTextReviewDetail(ctx context.Context, arg UpsertTextReviewDetailParams) error
}

var _ Querier = (*Queries)(nil)
