// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRun = `-- name: CreateRun :one
INSERT INTO runs (run_type, population_id, prompt_id, temperature, top_p, params, taxonomy_version)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type CreateRunParams struct {
	RunType         string         `json:"run_type"`
	PopulationID    int32          `json:"population_id"`
	PromptID        int32          `json:"prompt_id"`
	Temperature     pgtype.Numeric `json:"temperature"`
	TopP            pgtype.Numeric `json:"top_p"`
	Params          []byte         `json:"params"`
	TaxonomyVersion *int32         `json:"taxonomy_version"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (int32, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.RunType,
		arg.PopulationID,
		arg.PromptID,
		arg.Temperature,
		arg.TopP,
		arg.Params,
		arg.TaxonomyVersion,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getRun = `-- name: GetRun :one
SELECT id, run_type, population_id, prompt_id, temperature, top_p, params, created_at, taxonomy_version, config_digest FROM runs WHERE id = $1
`

func (q *Queries) GetRun(ctx context.Context, id int32) (Run, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.RunType,
		&i.PopulationID,
		&i.PromptID,
		&i.Temperature,
		&i.TopP,
		&i.Params,
		&i.CreatedAt,
		&i.TaxonomyVersion,
		&i.ConfigDigest,
	)
	return i, err
}

const listRunsByPopulation = `-- name: ListRunsByPopulation :many
SELECT id, run_type, population_id, prompt_id, temperature, top_p, params, created_at, taxonomy_version, config_digest FROM runs WHERE population_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListRunsByPopulation(ctx context.Context, populationID int32) ([]Run, error) {
	rows, err := q.db.Query(ctx, listRunsByPopulation, populationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.RunType,
			&i.PopulationID,
			&i.PromptID,
			&i.Temperature,
			&i.TopP,
			&i.Params,
			&i.CreatedAt,
			&i.TaxonomyVersion,
			&i.ConfigDigest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
