// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: worker.sql

package db

import (
	"context"
)

const getImageForIndividual = `-- name: GetImageForIndividual :one
SELECT a.id AS artifact_id, img.image_uri, img.mime_type, COALESCE(img.ocr_text, '')::text AS ocr_text
FROM individuals i
JOIN artifacts a ON a.id = i.artifact_id
JOIN image_details img ON img.artifact_id = a.id
WHERE i.id = $1
`

type GetImageForIndividualRow struct {
	ArtifactID int64   `json:"artifact_id"`
	ImageUri   string  `json:"image_uri"`
	MimeType   *string `json:"mime_type"`
	OcrText    string  `json:"ocr_text"`
}

func (q *Queries) GetImageForIndividual(ctx context.Context, id int64) (GetImageForIndividualRow, error) {
	row := q.db.QueryRow(ctx, getImageForIndividual, id)
	var i GetImageForIndividualRow
	err := row.Scan(
		&i.ArtifactID,
		&i.ImageUri,
		&i.MimeType,
		&i.OcrText,
	)
	return i, err
}

const getMultimodalForIndividual = `-- name: GetMultimodalForIndividual :one
SELECT a.id AS artifact_id, td.body, img.image_uri, img.mime_type
FROM individuals i
JOIN artifacts a ON a.id = i.artifact_id
JOIN text_review_details td ON td.artifact_id = a.id
JOIN image_details img ON img.artifact_id = a.id
WHERE i.id = $1
`

type GetMultimodalForIndividualRow struct {
	ArtifactID int64   `json:"artifact_id"`
	Body       string  `json:"body"`
	ImageUri   string  `json:"image_uri"`
	MimeType   *string `json:"mime_type"`
}

// a multimodal item carries both channels: a text body and an image. inner-joining both detail tables
// means it only returns artifacts that actually have both, which is exactly the multimodal case.
func (q *Queries) GetMultimodalForIndividual(ctx context.Context, id int64) (GetMultimodalForIndividualRow, error) {
	row := q.db.QueryRow(ctx, getMultimodalForIndividual, id)
	var i GetMultimodalForIndividualRow
	err := row.Scan(
		&i.ArtifactID,
		&i.Body,
		&i.ImageUri,
		&i.MimeType,
	)
	return i, err
}

const getTextReviewForIndividual = `-- name: GetTextReviewForIndividual :one
SELECT a.id AS artifact_id, td.body, td.voted_up, td.lang
FROM individuals i
JOIN artifacts a ON a.id = i.artifact_id
JOIN text_review_details td on td.artifact_id = a.id
WHERE i.id = $1
`

type GetTextReviewForIndividualRow struct {
	ArtifactID int64  `json:"artifact_id"`
	Body       string `json:"body"`
	VotedUp    bool   `json:"voted_up"`
	Lang       string `json:"lang"`
}

// text-specific query
func (q *Queries) GetTextReviewForIndividual(ctx context.Context, id int64) (GetTextReviewForIndividualRow, error) {
	row := q.db.QueryRow(ctx, getTextReviewForIndividual, id)
	var i GetTextReviewForIndividualRow
	err := row.Scan(
		&i.ArtifactID,
		&i.Body,
		&i.VotedUp,
		&i.Lang,
	)
	return i, err
}

const listUnnanotatedIndividuals = `-- name: ListUnnanotatedIndividuals :many
SELECT
    i.id as individual_id
FROM runs r
JOIN individuals i ON i.population_id = r.population_id
WHERE r.id = $1
    AND NOT EXISTS (
        SELECT 1 FROM annotations an
        WHERE an.run_id = r.id
            AND an.individual_id = i.id
            AND an.annotator_id = $2
            AND an.status = 'completed' 
    )
ORDER BY i.id
`

type ListUnnanotatedIndividualsParams struct {
	RunID       int32 `json:"run_id"`
	AnnotatorID int32 `json:"annotator_id"`
}

// The work queue for one panel member.
// Modality agnostic
func (q *Queries) ListUnnanotatedIndividuals(ctx context.Context, arg ListUnnanotatedIndividualsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listUnnanotatedIndividuals, arg.RunID, arg.AnnotatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var individual_id int64
		if err := rows.Scan(&individual_id); err != nil {
			return nil, err
		}
		items = append(items, individual_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
