// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: worker.sql

package db

import (
	"context"
)

const getTextReviewForIndividual = `-- name: GetTextReviewForIndividual :one
SELECT a.id AS artifact_id, td.body
FROM individuals i
JOIN artifacts a ON a.id = i.artifact_id
JOIN text_review_details td on td.artifact_id = a.id
WHERE i.id = $1
`

type GetTextReviewForIndividualRow struct {
	ArtifactID int64  `json:"artifact_id"`
	Body       string `json:"body"`
}

// text-specific query
func (q *Queries) GetTextReviewForIndividual(ctx context.Context, id int64) (GetTextReviewForIndividualRow, error) {
	row := q.db.QueryRow(ctx, getTextReviewForIndividual, id)
	var i GetTextReviewForIndividualRow
	err := row.Scan(&i.ArtifactID, &i.Body)
	return i, err
}

const listUnnanotatedIndividuals = `-- name: ListUnnanotatedIndividuals :many
SELECT
    i.id as individual_id
FROM runs r
JOIN individuals i ON i.population_id = r.population_id
WHERE r.id = $1
    AND NOT EXISTS (
        SELECT 1 FROM annotations an
        WHERE an.run_id = r.id
            AND an.individual_id = i.id
            AND an.annotator_id = $2
            AND an.status = 'completed' 
    )
ORDER BY i.id
`

type ListUnnanotatedIndividualsParams struct {
	RunID       int32 `json:"run_id"`
	AnnotatorID int32 `json:"annotator_id"`
}

// The work queue for one panel member.
// Modality agnostic
func (q *Queries) ListUnnanotatedIndividuals(ctx context.Context, arg ListUnnanotatedIndividualsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listUnnanotatedIndividuals, arg.RunID, arg.AnnotatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var individual_id int64
		if err := rows.Scan(&individual_id); err != nil {
			return nil, err
		}
		items = append(items, individual_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
