// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: worker.sql

package db

import (
	"context"
)

const getTextReviewForIndividual = `-- name: GetTextReviewForIndividual :one
SELECT a.id AS artifact_id, td.body
FROM individuals i
JOIN artifacts a ON a.id = i.artifact_id
JOIN text_review_details td on td.artifact_id = a.id
WHERE i.id = $1
`

type GetTextReviewForIndividualRow struct {
	ArtifactID int64  `json:"artifact_id"`
	Body       string `json:"body"`
}

// text-specific query
func (q *Queries) GetTextReviewForIndividual(ctx context.Context, id int64) (GetTextReviewForIndividualRow, error) {
	row := q.db.QueryRow(ctx, getTextReviewForIndividual, id)
	var i GetTextReviewForIndividualRow
	err := row.Scan(&i.ArtifactID, &i.Body)
	return i, err
}
